### ISSUE TITLE
Is there a easy way to decryt flow below android 6.0

### ISSUE THREAD

**Issue by hardcoresecz** [emanuele-f/PCAPdroid#10]

**Comment by hardcoresecz** [comment]
i read document from https://egorovandreyrm.com/pcap-remote-tutorial/#decrypting_https_tls_traffic , i think a decrypt module is usefuly, if above android 6.0 can use https://github.com/shroudedcode/apk-mitm to make it decrypt

**Comment by emanuele-f** [comment]
I wish to integrate decryption capabilities directly into PCAPdroid, please check out #9.
