### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by wanoghoco** [emanuele-f/PCAPdroid#103]
Gooday, please am having an error with the project cmake file. The error states: does not contain a CMakeList.text file

**Comment by emanuele-f** [comment]
Hi, please note that you can only build it on a Linux based distro. If so, please report the exact steps and the full error message you receive.

**Comment by wanoghoco** [comment]
Please am using a windows machine, are u trying to say this project only
works on a Linux distribution

**Comment by emanuele-f** [comment]
Yes, it depends on some build tools of Linux. See https://github.com/emanuele-f/PCAPdroid#building . My suggestion is to build it into an ubuntu vm, you can call the grade build from the cli

**Comment by wanoghoco** [comment]
Ok thanks allot...

**Comment by emanuele-f** [comment]
It's now possible to build the app in Windows. Ensure to pull the latest master and check out the new instructions https://github.com/emanuele-f/PCAPdroid#building

**Comment by wanoghoco** [comment]
Thanks allot

**Comment by wanoghoco** [comment]
Good day sir.. please am very sorry to disturb you. I would like if you
could explain how I can get only the url or request made by all apps as
implemented by your PCAPdriod.. please sir

**Comment by emanuele-f** [comment]
The app uses nDPI to extract such info from the traffic https://github.com/ntop/nDpi
