### ISSUE TITLE
Ability to extract full http (probably with websockets) data

### ISSUE THREAD

**Issue by NEK-RA** [emanuele-f/PCAPdroid#107]
While most sites today served with SSL, I guess that's not important until PCAPdroid will get it's own built-in TLS decryption module/service(what's more correct)

The requested functionality is:

- [x] show headers and body for http request
- [x] show headers and body for http response
- [ ] if `Content-Type` header says that response isn't text or json, then probably display limited amount of data
- [ ] websockets support may be not so important, but I guess that it will be nice addition sometime in future

Not sure, but for displaying data may be some webview section will be usefull, as I think, because it more "universal" and may be used to display:

- preview for http response (if it's html or media)
- code of response highlited with something like PrismJS and probably formated with something else

For the unknown MIME types or binary files, probably there's suitable the button to "export as file", because if I'm not mistaken, exported PCAP still contain all responses including binary data.

Probably this can be done as optional feature which may be turned on/off from settings, as well, as set limit for amount of data to be displayed for non-media/html data

P.S.: done as mentioned to create issue in chat message - https://t.me/PCAPdroid/2992

**Comment by emanuele-f** [comment]
With 35cdd7086b74b9f7972cb36f5f9cbf9875f2dc07 PCAPdroid has now the ability to display the full payload.

What won't probably be supported:
- HTML/images preview: we are capturing the device own traffic so this feature has little use
- code/JSON highlighting/format: this seems overkill for now
- export of binary files: this seems overkill for now, little use

The tradeoff between memory usage and level of details can be selected via the "Payload visualization" option.

<img src="https://user-images.githubusercontent.com/5488003/159325677-a004e60d-9efe-4763-af95-3ecf5a47b354.png" width="200">
 
The default "short payload" option is to only show 1 request packet and 1 reply packet (up to 512 B each). This is similar to the current behavior. With "full payload" all the packets data is saved in the RAM. Ideally this should only be used when targeting a specific app, as the impact on RAM usage is huge (if you capture 1 GB traffic it will take 1 GB ram).

The most common HTTP request/responses encodings are parsed and the resulting plaintext string is displayed. Websocket is currently only supported when TLS decryption is enabled.

<img src="https://user-images.githubusercontent.com/5488003/159326426-549b3cba-9fac-4610-96a9-85fea021eff4.png" width="200"/> <img src="https://user-images.githubusercontent.com/5488003/159326485-9c5d161a-31e8-41e1-87fb-12ffd7cd33d2.png" width="200"/>

The payload tab shows the hexdump of the payload regardless of the protocol. Egress/ingress packets are shown with different colors and marked with TX/RX.

<img src="https://user-images.githubusercontent.com/5488003/159327028-0c3e7918-7480-4b74-adc1-4d21a384577e.png" width="200">

When combined with the new TLS decryption feature, PCAPdroid displays the decrypted payload.

<img src="https://user-images.githubusercontent.com/5488003/159327378-b8557ec0-e779-4b24-b907-5527e9656b7e.png" width="200">

**Comment by MadTooth** [comment]
Beautiful PCAP program by greatest programmer

**Comment by MadTooth** [comment]
Beautiful PCAP program by greater programmer

**Comment by emanuele-f** [comment]
ab4ac8f2724d7bbd55316e721a479e33fdb98c5e and 1895b0198b36316e1dddb1ff6400a30b91a306a2 fix UI freezes when opening a connection with a long payload, by collapsing the payload and making it paginated.

With 64721ea64cc78442e8536c5d2f4518b5bf7934dd the HTTP requests and replies are now interleaved into a single tab. An arrow makes it simple to jump from an HTTP request to its reply and vice-versa.

<img src="https://user-images.githubusercontent.com/5488003/163042452-247aa6c2-7560-462a-86ff-1e78165a0d26.jpg" width="200"/>

This completes the set of features for this issue. New features will be discussed in separate issues.
