### ISSUE TITLE
PCAPdroid in root capture seems to be missing traffic

### ISSUE THREAD

**Issue by ioogithub** [emanuele-f/PCAPdroid#111]
I have been comparing the logging results of AFWall+ (iptables frontend) and PCAPdroid in root capture. AFWall+ is logging outgoing traffic from apps that that PCAPdroid doesn't see at all. For example:

AFWall logs outgoing requests requests from the GPS app. In roughly 60 minutes, there were 84 packets to 28 different IP addresses on port 443 recorded.

If I search PCAPdroid, I can't see any of these IP addresses and the GPS app isn't even shown under apps at all. The IP addresses are not under unknown either.

According to the description: https://emanuele-f.github.io/PCAPdroid/advanced_features#44-root-capture, if PCAPdroid is capturing the real packets on the interface in RAW mode then shouldn't this traffic be detected?

**Comment by emanuele-f** [comment]
Are you blocking such traffic with a firewall? If so, they don't reach the nic so Pcapdroid cannot see them. Also ensure that you are using the latest app version (1.4.1)
