### ISSUE TITLE
PCAP file is not generated normally when stop capture[device:Huawei phone, Android R]

### ISSUE THREAD

**Issue by AskaMgl** [emanuele-f/PCAPdroid#122]
Hi Emanuele,

We found that on Huawei devices, there will be an isuue that the file cannot save files when the pcap capture for a long time, pls help to check.

//start capture
09-23 21:57:07.063 32448 32448 D CaptureService: onStartCommand
09-23 21:57:07.064 32448 32448 D FileDumper: PCAP URI: content://com.android.providers.downloads.documents/document/24

//end capture
09-23 23:10:30.079 32448  6920 D VPNProxy: Host LRU cache ADD [v4]: 113.59.42.230 -> mssdk-bu.snssdk.com
09-23 23:10:30.079 32448  6920 D VPNProxy: Host LRU cache ADD [v4]: 113.59.42.104 -> mssdk-bu.snssdk.com
09-23 23:10:30.079 32448  6920 D VPNProxy: Host LRU cache ADD [v4]: 113.59.42.101 -> mssdk-bu.snssdk.com
09-23 23:10:30.079 32448  6920 D VPNProxy: Host LRU cache ADD [v4]: 182.89.221.224 -> mssdk-bu.snssdk.com
09-23 23:10:30.079 32448  6920 D VPNProxy: Host LRU cache ADD [v4]: 113.59.42.108 -> mssdk-bu.snssdk.com
09-23 23:10:30.079 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=17] -> l7proto: app=5, master=5
09-23 23:10:30.333 32448 32448 D MainReceiver: Got StatsUpdate: bytes_sent=7472, bytes_rcvd=40824957, pkts_sent=7472, pkts_rcvd=28680
09-23 23:10:30.580 32448  6920 D VPNProxy: sendConnectionsDump [after 1324 ms]: new=4, updates=2
09-23 23:10:30.580 32448  6920 D ConnectionsRegister: connectionsUpdates: items=314, first_id=0, last_id=313
09-23 23:10:30.831 32448  6920 D VPNProxy: Exporting a 170504 B PCAP buffer
09-23 23:10:31.588 32448 32448 D MainReceiver: Got StatsUpdate: bytes_sent=7472, bytes_rcvd=40824997, pkts_sent=7472, pkts_rcvd=28681
09-23 23:10:31.834 32448  6920 D VPNProxy: sendConnectionsDump [after 1252 ms]: new=0, updates=1
09-23 23:10:31.834 32448  6920 D ConnectionsRegister: connectionsUpdates: items=314, first_id=0, last_id=313
09-23 23:10:31.963 32448 32448 V AudioManager: querySoundEffectsEnabled...
09-23 23:10:31.965 32448 32448 I VPNProxy: stopPacketLoop called
09-23 23:10:31.965 32448 32448 D CaptureService: Joining native thread...
09-23 23:10:32.085 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=6] -> l7proto: app=91, master=91
09-23 23:10:32.085 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=6] -> l7proto: app=91, master=91
09-23 23:10:32.086 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=6] -> l7proto: app=222, master=222
09-23 23:10:32.094 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=6] -> l7proto: app=91, master=91
09-23 23:10:32.094 32448  6920 D VPNProxy: nDPI completed[ipver=4, proto=6] -> l7proto: app=91, master=91
09-23 23:10:32.094 32448  6920 D VPNProxy: Stopped packet loop
09-23 23:10:32.097 32448  6920 D VPNProxy: Exporting a 5096 B PCAP buffer
09-23 23:10:32.098 32448  6920 D VPNProxy: Host LRU cache size: 256
09-23 23:10:32.098 32448  6920 D VPNProxy: Discarded fragments: 0
09-23 23:10:32.540 32448 32448 I Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
09-23 23:10:32.542 32448 32448 D Main    : Service status: stopped
09-23 23:10:32.542 32448 32448 D Main    : showPcapActionDialog: content://com.android.providers.downloads.documents/document/24
**09-23 23:10:32.602 32448 32448 D Main    : PCAP file is empty, deleting**

Thanks a lot.

**Comment by emanuele-f** [comment]
Which Android version? Before stopping the capture, can you verify if the file exists in the internal storage and which is its size? [Here is](https://github.com/emanuele-f/PCAPdroid/blob/8bb1ff3caf619579793fddf0efb049c9340648ac/app/src/main/java/com/emanuelef/remote_capture/activities/MainActivity.java#L562) the check for the file size.

**Comment by emanuele-f** [comment]
No feedback received, closing.
