### ISSUE TITLE
Integrate PACPdroid into my app can not get result

### ISSUE THREAD

**Issue by GirlLily** [emanuele-f/PCAPdroid#131]
Hi, Emanuele,
I integrated the exposed API to my app, but can't get the result of traffic and number of packets. The result code is okay, but the data is null. So I think the command succeeded. But I don't know why I can't get the traffic.
![image](https://user-images.githubusercontent.com/26410190/138695729-6de43b98-8daf-4e66-a2c8-34f02a24e0f2.png)

**Comment by emanuele-f** [comment]
That are just the TCP options. Please check out the pcap4j docs to learn how to use it, this is off topic here. If you need consulting for your app please reach me via email. Closing this as all the questions pertinent to PCAPdroid should now be clarified.

**Comment by GirlLily** [comment]
Great thanks! May I have your email?

Emanuele Faranda ***@***.***>于2021年10月30日 周六11:29写道：

**Comment by emanuele-f** [comment]
You can find it in the [sponsors section](https://github.com/emanuele-f/PCAPdroid#sponsors)

**Comment by GirlLily** [comment]
Btw, I want to loop to get the packet of an app list. How to let the
request just show one time. Coz request window pop up every time when
listen to a new app.

Emanuele Faranda ***@***.***>于2021年10月30日 周六11:45写道：

**Comment by emanuele-f** [comment]
Pleas open a new feature request. This must be implemented in a way that users can give, review and revoke their consent
