### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#14]
PCAPdroid is a fully open source project. Making it available on F-Droid will increase its visibility and facilitate the life of some foss users.

**Comment by emanuele-f** [comment]
Submission: https://gitlab.com/fdroid/rfp/-/issues/1620

**Comment by emanuele-f** [comment]
Merged! Will soon be available in the official repository

**Comment by beedell-roke** [comment]
@emanuele-f, Per https://github.com/emanuele-f/PCAPdroid/issues/470#issuecomment-2543967891, is this not complete anymore? I don't see it listed at F-Droid, despite https://github.com/emanuele-f/PCAPdroid/issues/511#event-17415305501. I see [`8b87f8ee633a7c41d4db913b8819b552bf161fd9/README.md?plain=1#L38`](https://github.com/emanuele-f/PCAPdroid/blob/8b87f8ee633a7c41d4db913b8819b552bf161fd9/README.md?plain=1#L38), but that's inequivalent.

**Comment by emanuele-f** [comment]
See https://f-droid.org/it/packages/com.emanuelef.remote_capture/
