### ISSUE TITLE
Add ability to block connections - firewall

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#144]
PCAPdroid can already match connections against a list of rules. These can be used to create a user-defined block-list to block connections. This mode should be available both when running in VPNService and in root mode. The first is trivial to implement as we are already inline with the traffic. The latter is more complex as it requires relying on linux facilities like in #128.

- [x] non-root firewall: ability to block IP, domain or app
- [x] early blocking for domains (e.g. DNS queries)
- [x] malware but whitelisted connections must not be blocked
- [x] ability to import/export rules (5facf66)
- [x] firewall: on-off toggle (51224ac)
- [x] blocked connections stats: global, per app (51224ac)
- [x] subdomain matching (bc5589d)
- [x] add app icon in the blocklist (67dae23)
- [x] long tap an app and block it (3be18fb)
- [x] unblock connections from the context menu (af2df84)
- [x] docs: inform about DownloadManager leaks and about DNS connections blocking ([docs](https://emanuele-f.github.io/PCAPdroid/paid_features#51-firewall))

An issue with blocking connections is that some apps perform continuous retries when their connections are blocked (also happens with DNS requests). In my case, this was mainly visible overnight when the device is connected to the power socket.

**Comment by emanuele-f** [comment]
Initial implementation for no-root mode in 62c84f96631c104bf0bcdf3e622c0c31bc84ab48

**Comment by K-techie** [comment]
A few suggestions on enhancement of Firewall feature would include -
1. Allow unblocking of an app or IP/host from connections menu itself by long pressing the blocked connection.
2. Allow us to block a particular App or ip/host at the starting of a capture i.e even before it shows up in the connection Tab.
3. A more better visual look to the the "Firewall rules page" which may include the App icons of Apps blocked and other additional stats besides it as mentioned in earlier comment.
