### ISSUE TITLE
Ipv6 address is set to fallback on enabling ipv6 capture

### ISSUE THREAD

**Issue by K-techie** [emanuele-f/PCAPdroid#161]
On enabling ipv6 capture , the ipv6 address is set to fallback and ipv4 address is being used instead as default for making the connections.
This would not serve the purpose very well for users who may prefer to capture the traffic in ipv6 with sites/domain which support them.
As tested in the current v1.4.4 , the apps and browser sites mostly use ipv4 connections even when a ipv6 address is available and the site/domain  supports ipv6.
As in the coming years , ipv6 would be more widely adopted ,so this would need to be fixed to give accurate results.
![pcapdroid_ipv6](https://user-images.githubusercontent.com/93819980/143039595-7dd58b0e-3e36-4726-88ff-55677d23e8ae.jpg)
Picture showing ipv6 being made to fallback. 
(Also shown is the weird number of dns servers detected which maybe due to their website error) 
My normal internet connection does uses ipv6 as default as i checked it when the capture was not running.
The above problem is detected in version 1.4.4 using non-root method  and with private dns set to automatic.

**Comment by emanuele-f** [comment]
When the IPv6 option of PCAPdroid is enabled, PCAPdroid sets both an IPv4 and an IPv6 address in the VPNService network connection. It's up to the system to select which IP address version to use, PCAPdroid has no control of it. I can only provide an IPv6 only mode but I want to better understand your needs on this topic.

**Comment by K-techie** [comment]
There is no such particular use case for me , but wanted to ensure that the connections that are captured during 
 pcapdroid vpn session would resemble the same type of connections an app would make (i.e if ipv6 /ipv4 used) if a vpn service wasn't running. 
Since as you mentioned that pcapdroid has no control over it,  the only question remains is that 
if the behavior of an app would change in terms of using ipv6/4 when it connects via VPN service as compared to a non-vpn  connection which can be observed through root capture.
since i am not having root , i don't know whether , the VPN service would have any effect on how the apps chose to connect..

**Comment by emanuele-f** [comment]
It does affect how apps connect, this is explained in the [packet analysis section](https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis) of the manual. Without root, capture is only possible with such limitations.

**Comment by K-techie** [comment]
Thanks , the manual makes it clear to understand👍
