### ISSUE TITLE
Displaying the contents of the "connection" information as in the "Packet Capture" program

### ISSUE THREAD

**Issue by MadTooth** [emanuele-f/PCAPdroid#189]
Can you make the contents of the "connection" information display like in the "Packet Capture" program ? [app.greyshirts.sslcapture]

Example:
![S_20220215_235309](https://user-images.githubusercontent.com/30464341/154112773-93e9d50b-e0a7-4b9d-8ae9-ba512971518e.jpg)
![S_20220215_235342](https://user-images.githubusercontent.com/30464341/154112877-20d32cfb-2f3d-4fdf-9619-737381e86887.jpg)
![S_20220215_235419](https://user-images.githubusercontent.com/30464341/154113000-6985d994-6f33-4c67-b576-7fd0cf7f1294.jpg)

**Comment by emanuele-f** [comment]
Thank you for the suggestion, merging this with #107

**Comment by MadTooth** [comment]
You are a great and helpful android programmer !
