### ISSUE TITLE
UDP traffic missing?

### ISSUE THREAD

**Issue by 2011** [emanuele-f/PCAPdroid#191]
Had some app that kept a constant connection (viewable by network bandwidth displayed on the status bar). Installed PCAPdroid (1.4.7 on a rooted Android 7 device) to diagnose. App showed basically no connections other than an occasional random packet. Ran tcpdump from a root shell and saw constant UDP traffic between the device and a remote server (eventually started killing apps until I determined the offending one). Far from an expert at this by any measure, but shouldn't PCAPdroid show UDP traffic as well as TCP (and DNS, ICMP, and other minor protocols)?

PCAPdroid has a huge amount of potential, and I do thank you very much for creating it (and for addressing this question :) ).

**Comment by K-techie** [comment]
As far as my knowledge goes Pcapdriod does support all protocols and if you capture in root mode (with all interfaces on) it's highly unlikely that any connection would be hidden from pcapdroid.

**Comment by emanuele-f** [comment]
> shouldn't PCAPdroid show UDP traffic as well as TCP (and DNS, ICMP, and other minor protocols)?

In non-root mode PCAPdroid uses the Android VPNService, which only captures the connections which are initiated from the device (e.g. started from the device to the Internet). So ensure that this is the case for your UDP connection. PCAPdroid supports TCP, UDP and ICMP and any protocols on the top of them (e.g. DNS).

As K-techie said, if you (want full visibility on the traffic)[https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis] then you should run PCAPdroid on a rooted device and enable the root capture.

**Comment by 2011** [comment]
I do have root mode enabled, and did run it in root mode. The UDP traffic just did not show up in PCAPdroid.

**Comment by 2011** [comment]
I have root mode enabled, and do use root capture mode.

I just tried again (changing "Capture interface" from "Internet" to "All interfaces"), which shows some regular traffic.  PCAPdroid now shows thousands of packets such as these:

```
Unknown           Closed
TLS 40001       21:40:00
127.0.0.1          100 B

Unknown           Closed
TLS 40002       21:40:00
127.0.0.1          100 B

Unknown           Closed
TLS 40003       21:40:00
127.0.0.1          100 B

[...]
```

The tcpdump at the same time looks like this (a constat stream of packets):

```
# /system/xbin/tcpdump -v                                         
tcpdump: listening on wlan0, link-type EN10MB (Ethernet), capture size 262144 bytes
21:40:00.134662 IP (tos 0x0, ttl 64, id 34301, offset 0, flags [DF], proto UDP (17), length 124)
    192.168.0.1.57411 > unn-84-17-41-140.cdn77.com.51820: UDP, length 96
21:40:00.136004 IP (tos 0x0, ttl 53, id 18753, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
21:40:00.136079 IP (tos 0x0, ttl 53, id 18754, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
21:40:00.136570 IP (tos 0x0, ttl 64, id 34302, offset 0, flags [DF], proto UDP (17), length 124)
    192.168.0.1.57411 > unn-84-17-41-140.cdn77.com.51820: UDP, length 96
21:40:00.138756 IP (tos 0x0, ttl 53, id 18755, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
21:40:00.138884 IP (tos 0x0, ttl 53, id 18756, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
21:40:00.139335 IP (tos 0x0, ttl 64, id 34303, offset 0, flags [DF], proto UDP (17), length 124)
    192.168.0.1.57411 > unn-84-17-41-140.cdn77.com.51820: UDP, length 96
21:40:00.144697 IP (tos 0x0, ttl 53, id 18757, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
21:40:00.144818 IP (tos 0x0, ttl 53, id 18758, offset 0, flags [none], proto UDP (17), length 1340)
    unn-84-17-41-140.cdn77.com.51820 > 192.168.0.1.57411: UDP, length 1312
```

If I change "Capture interface" to "wlan0"), then I do see (I believe only the outbound) UDP traffic:

```
Unknown             Open
UDP 51820       22:00:00
84.17.41.140     22.0 KB
```

I don't see any other connections, though (other than an occasional MDNS packet).

**Comment by 2011** [comment]
I have looked at this some more, and decided that the traffic monitor (displayed in the status bar) simply overstates (vastly) the traffic that the app in question produces. Those numbers indicate a near-constant 30 KB/s, but I see (at most) a couple of packets per second (either length 31 or acknowledgement of those with zero length). I don't know why I trusted the system traffic monitor rather than your app, but obviously, I made a mistake. In addition, I didn't enhnace my understanding by running tcpdump on the wrong interface. Sorry.

**Comment by emanuele-f** [comment]
Different tools often show different kind of information, so it's normal to be concerned about this. Just as an example, a common misconception is that capturing packets with tcpdump on an host will give you the real network packets, but most of the time this is not true, as the os aggregates packets with techniques like TSO, GSO and GRO (generic receive offload) so you get packets bigger than the mtu. In short, only by learning the limitations of the tools and technologies you can understand what's really going on
