### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [emanuele-f/PCAPdroid#192]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 5 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on PCAPdroid (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve PCAPdroid' security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by emanuele-f** [comment]
Hi, thank you for analyzing PCAPdroid, I'm curious to know how you got to know this project. Any security vulnerability should be fixed asap, so please share the details of your analysis to very them. You can reach me at black.silver@hotmail.it for sensitive information

**Comment by emanuele-f** [comment]
@misterAnderson90 any news? Looking at your submissions in other repos and I didn't see relevant activity, are your claims verifiable? Moreover, this issue title seems misleading as PCAPdroid does not use cryptographic APIs as far as I know

**Comment by misterAnderson90** [comment]
Hello @emanuele-f,

I got to know about this project by searching for Android applications from the [Security Category of F-Droid](https://f-droid.org/en/categories/security/). I'm conducting research to evaluate the perception of the developers concerning the warnings reported by this SAST. 

I have sent you the e-mail with the reported warnings. Could you please evaluate them? 

Thanks for your contribution.

**Comment by emanuele-f** [comment]
Thank you for your report. The reported problems are confined into the billing logic of the app (Billing.java). After evaluation I confirm these are in line with the security expectations of such a class and in any case do not affect the security of the app.
