### ISSUE TITLE
maxmind db error

### ISSUE THREAD

**Issue by WanderingCoder-Omen** [emanuele-f/PCAPdroid#193]
Tried to build the project in Android Studio and I'm getting a few error related to maxmind db.

Examples

\Android\PCAPdroid\app\src\main\java\com\emanuelef\remote_capture\model\Geomodel.java:64: error: cannot find symbol
                @MaxMindDbParameter(name="autonomous_system_number") long number,
                 ^
  symbol:   class MaxMindDbParameter
  location: class ASN
\Android\PCAPdroid\app\src\main\java\com\emanuelef\remote_capture\model\Geomodel.java:65: error: cannot find symbol
                @MaxMindDbParameter(name="autonomous_system_organization") String asname) {
                 ^
  symbol:   class MaxMindDbParameter
  location: class ASN

**Comment by emanuele-f** [comment]
Ensure to pull all the git submodules: `git submodule update --init`

**Comment by emanuele-f** [comment]
No feedback received, closing
