### ISSUE TITLE
Ability to start/stop capture from shortcuts/quick settings

### ISSUE THREAD

**Issue by MadTooth** [emanuele-f/PCAPdroid#202]
> Tile - [Record/Stop] 

>LongTap on Icon [PCAPdroid] - [Record/Stop]

Examples [Pics]:
![S_20220502_230336](https://user-images.githubusercontent.com/30464341/166268252-3b7fd165-5703-48e6-8446-26b7e146b415.jpg)
![S_20220502_230149](https://user-images.githubusercontent.com/30464341/166268163-e86fb534-7cab-4cfd-8eab-795c520fc481.jpg)

**Comment by emanuele-f** [comment]
What's this?

**Comment by MadTooth** [comment]
> What's this?

LongTap & Tile

Uploading MP4_20220503_180118.mp4…

**Comment by MadTooth** [comment]
> What's this?

LongTap on Icon & Tile

https://user-images.githubusercontent.com/30464341/166442312-2e2c4309-ac94-457b-a6a9-89c7a8f24a07.mp4

https://user-images.githubusercontent.com/30464341/166442353-e2d9706d-5e62-4a25-a7fb-7cce14bbb377.mp4

**Comment by emanuele-f** [comment]
Issue title modified. Try to explain with words next time, use a translator if english is not your native language.

Additional API references:
- [Shortcuts](https://developer.android.com/guide/topics/ui/shortcuts)
- [Quick settings](https://developer.android.com/reference/android/service/quicksettings/TileService)

**Comment by MadTooth** [comment]
Thanks, MasterDroid
