### ISSUE TITLE
Add ability to manually add rules (e.g. firewall rules)

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#207]
Right now it's only possible to add a rule by long pressing a connection. It should be added the ability to add an arbitrary rule manually.

**Comment by karano-techie** [comment]
For manually adding rules  , in case of apps , a page showing list of all apps with a toggle besides them to block/unblock ,would be very handy to a user.
For host/ip rules a separate page (tab) should be made for easier understanding/navigation of firewall rules.

**Comment by ignoramous** [comment]
(*rdns dev here*)

We use seancfoley's [`IPAddress` library](https://github.com/seancfoley/IPAddress), and it really simplified this feature for us. It supports wildcards, classful addresses, and host:port format for both IPv4 and IPv6. Also bakes in nifty functions like extracting out IPv4 if embedded in IPv6 addresses (needed for firewall rules).

Highly recommend.

**Comment by kevino-techie** [comment]
@emanuele-f  what about adding a link to https://pcapdroid.org/hosts.html in the app itself in the firewall menu.

It will help people to import other blocklist but which is in different format.
I think it would be a good idea to link it somewhere in the app rather than in the user guide.

**Comment by emanuele-f** [comment]
> @emanuele-f what about adding a link to https://pcapdroid.org/hosts.html in the app itself in the firewall menu.
Due to #284 is currently not advisable to add a big number of rules to the app. This feature was meant to provide a way for users to block specific apps/domains, not to support large blacklists. Standard formats could be supported directly in the app, without the need to convert them via the website, but there are some implications, e.g. ad-blocking is not permitted in Google Play.
