### ISSUE TITLE
Implement DNS-over-TLS client

### ISSUE THREAD

**Issue by DGDG14** [emanuele-f/PCAPdroid#211]
Please add the secure DNS OR CUSTOM DNS option to get privacy.
For example
Once traffic is processed from pcapdroid than it will directly go to router and then it will go to the service provider DNS and then it will go to the destination this currently happening.
And I'm thinking of this  once traffic is process by pcapdroid at the end of VPN tunnel   add option for where traffic needs to be sent user can select to add custom DNS or a secure DNS.
for secure DNS there are many free secure DNS for example adguard DNS or CLOUDFLARENET DNS and many more which you can also provide as list of DNS
I know this is kind complicated request.
This could help alot VISIBILITY WITH PRIVACY.

**Comment by karano-techie** [comment]
Implementing a dns over tls client could provide additional info about the  connections made to a certain domians particularly which are made through quic protocol which won't give out the sni too.
Also in decryption mode , it could be useful to keep outgoing requests secure.
Though priority of this request could be evaluated by the dev.

**Comment by emanuele-f** [comment]
https://github.com/Gedsh/InviZible#dnscrypt can provide useful ideas for integration

**Comment by karano-techie** [comment]
> Also in decryption mode , it could be useful to keep outgoing requests secure.\nThough priority of this request could be evaluated by the dev.

For providing secure dns queries in tls decryption mode , the reverse-dns mode of mitmproxy could be used. The tag for specifing an upstream dns server is ```
--mode reverse:dns://8.8.8.8
```
refer mitmproxy documention regarding this [here](https://docs.mitmproxy.org/stable/concepts-modes/#dns-server)
Replace google dns with cloudflare dns

**Comment by emanuele-f** [comment]
PCAPdroid can now be used in conjunction with InviZible Pro, to encrypt the DNS traffic with DNSCrypt/DNS-over-HTTPS 
see https://emanuele-f.github.io/PCAPdroid/advanced_features#42-doh-support for more details.
Integrating dnscrypt-proxy directly could be possible in the future but it's involved, both because it will probably require relying on pre-built executables and because the UI for the DNSCrypt settings needs to be implemetend in PCAPdroid
