### ISSUE TITLE
How to show App name column in Wireshark?

### ISSUE THREAD

**Issue by 737simpilot** [emanuele-f/PCAPdroid#219]
I placed the lua scripted plugin in the plugins folder, Wireshark appears to have loaded it, but I don't see that column option. I tried editing and adding columns and no "App" column name appears.

**Comment by emanuele-f** [comment]
Ensure that the plugin is loaded, then in the packet trailer right click on the App field and select "Apply as column"

**Comment by 737simpilot** [comment]
I don't seem to have that option. Using Windows and the latest version of Wireshark 64 bit. I right click the trailer with the long string of numbers and the App field is not present. 


![img](https://i.postimg.cc/59QrSr7H/this.jpg)

**Comment by emanuele-f** [comment]
The plugin is probably not loaded correctly. The screenshot in https://emanuele-f.github.io/PCAPdroid/advanced_features#45-pcapdroid-trailer shows how the trailer looks like when the plugin is correctly loaded. Ensure that its extension is `.lua` and not `.lua.txt`. Try to ask for help on the Wireshark communities if you still have issues

**Comment by 737simpilot** [comment]
Sorry for the late reply. Yes, I made sure the extension was correct as you can see in my screenshot. 

I don't know, it _may_ be a Windows thing. Especially since I can't use monitor mode in Wireshark with an Alfa WiFi NIC. 

I'll ask on the Wireshark forum and try this in a Linux VM.

**Comment by emanuele-f** [comment]
Closing for now. Talking about Alfa nics, you may be interested in my no-root app to capture packets in monitor mode on Android https://play.google.com/store/apps/details?id=com.usbwifimon.app

**Comment by 737simpilot** [comment]
Hey, now that looks pretty cool! I defiantly will be checking that out! I saw a YouTube video of how to locate hidden WiFi cameras at places like an Airbnb or hotels using monitor mode to zero in on the location, so this would be an outstanding way to do it rather than use a laptop. 

I have yet to try  Wireshark in Linux for PCAPDroid, but it's on the list. Chances are it'll work as intended. It seems like Wireshark just isn't 100% fully functional under Windows.

**Comment by emanuele-f** [comment]
> locate hidden WiFi cameras at places like an Airbnb or hotels using monitor mode

The app allows you to do this, as you can see all the wifi clients associated with the different access points and their signal strength. This is similar to the `airodump` linux tool

> I have yet to try Wireshark in Linux for PCAPDroid, but it's on the list

The key point to enable monitor mode for your wireless interface. In linux, this is quite easy with the `airmon` tool. My Android app will just work, as long as you have a supported wifi adpater (chipset AR9270)

> It seems like Wireshark just isn't 100% fully functional under Windows

This is probably a driver issue for the monitor mode. It will probably work on linux, supposing that your card driver supports monitor mode (e.g. ath9k)

**Comment by 737simpilot** [comment]
Can the App support something like the Alfa **AWUS036ACM**   ? This is what I own and it cost me a lot. I thought it had the AR9271 chipset but doesn't. 

One more Q:

Do I need external power on the USB OTG cable as well? 

I'd ask these questions on the proper Github page, but as you say this App is closed source. Totally fine though. 


Thanks again!

**Comment by emanuele-f** [comment]
AWUS036ACM has a mediatek chipset, which uses a totally different driver. Even if it will be a lot of work, it's something I'd like to support in the future, as such chipset supports the 5 Ghz band while the ar9271 does not. Please note that you can buy cheap adapters on aliexpress (use "ar9271" as the search keyword) for about 10 euros (e.g. chaneve), and they work very well. Just be sure to avoid the ones with internal antenna, as they have very short range.

You don't need external power for the otg.

You can contact me via email for more info.

**Comment by 737simpilot** [comment]
Thank you. I'm going to buy the Alfa I saw on eBay with the ar9271 chipset.
