### ISSUE TITLE
Using a custom server in place of PCAPdroid's HTTP server

### ISSUE THREAD

**Issue by Alluseri** [emanuele-f/PCAPdroid#222]
Hello. Is it possible to make PCAPdroid redirect the traffic at a custom IP address instead of its own HTTP server? I have Fiddler running on my PC and I have made it accessible from mobile, and I want to use that because mitm's HTTPS/TLS decryption usually fails and I didn't find a WebSocket message interception feature.

I do not have root so I believe that if I try compiling this app manually with necessary changes it would void the CA certificate used and it just wouldn't work for me.

**Comment by emanuele-f** [comment]
Hi, in the PCAPdroid settings you can enable the SOCKS5 redirection, which allows you to redirect the traffic to any SOCKS5 server (e.g. mitmproxy/fiddler)

**Comment by Alluseri** [comment]
Oh, really? I did see that setting but I didn't know that Fiddler is a SOCKS5 proxy server, my bad. Thanks for the help.
