### ISSUE TITLE
PCAPdroid tries to establish IPv4 connections in an IPv6-only network

### ISSUE THREAD

**Issue by Slaine68** [emanuele-f/PCAPdroid#223]
I try to capture the network traffic In an IPv6-only network, but when the VPN is established, the network access would become much slower. It usually takes more than 20s to load images. I tried to analyze the pcap files and found that when the DNS server returned an IPv4 address first, the application would keep trying to connect the service with IPv4 address and being failed. I guess that's probably the reason. Would you give me some advices? And are there has any plan to add an IPv6-only mode?

**Comment by emanuele-f** [comment]
An IPv6-only mode must be added

**Comment by Slaine68** [comment]
Thank you for the reply!
I'd appreciate it if I could know the approximate time plan. PCAPdroid is really helpful for my current work, thus Im so care about it.

**Comment by emanuele-f** [comment]
This is now implemented. Check out [the debug apk](https://github.com/emanuele-f/PCAPdroid/suites/7140893784/artifacts/283812846) built in the github workflow and let me know if it works for you. If you find this project useful, please consider [making a donation](https://emanuele-f.github.io/PCAPdroid/donate).

**Comment by Slaine68** [comment]
It works well, and the quality of packets collected in IPV6-only mode is good enough for me. Later I'll get my friends to donate, for I don't have a paypal account...😉 Thanks again for your quick response, it helped me a lot!
