### ISSUE TITLE
Filtering for http includes https

### ISSUE THREAD

**Issue by opk12** [emanuele-f/PCAPdroid#228]
Most connections on my phone are https. I want to find the http ones. Ideally, the list would be very short and easy to read, however filtering for `http` includes https, so I need to skim through a very long list. This was easy to do with the plaintext filter, which is gone now.

PS This app is awesome

**Comment by emanuele-f** [comment]
Searching `http` will now only match `http`. Moreover, a new "cleartext only" filter is available.

You can test this feature before the official the release from [the beta repository](https://pcapdroid.org/fdroid/repo/)
