### ISSUE TITLE
Add firewall whitelist (block-all) mode

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#232]
In this mode all the connections are blocked unless manually whitelisted via rules

**Comment by emanuele-f** [comment]
PCAPdroid provides a default whitelist to avoid essential services disruption: https://github.com/emanuele-f/PCAPdroid/blob/9eed9ed2217e022b43b329c3141e948bfd0e85d0/app/src/main/java/com/emanuelef/remote_capture/PCAPdroid.java#L130 @kevino-techie do you know other packages to be added?

**Comment by emanuele-f** [comment]
Additional info: the new feature can be enabled from the Firewall status page:

![2022-12-01_22-28](https://user-images.githubusercontent.com/5488003/205163253-e1eccd68-60a8-46ca-aa06-ce40b1abe839.png)

When enabled, a new tab appears, containing the list of whitelist rules:

![2022-12-01_22-30](https://user-images.githubusercontent.com/5488003/205163399-7b51d06b-48ea-449c-843e-56cdb3f0857c.png)

Whitelist rules works together with the blocklist. First the blocklist is checked to determine if a connection should be blocked, then the whitelist. This allows us to block specific domains even in whitelist mode.

It's only possible to whitelist a whole app. The app can be whitelisted from the connection context menu, by selecting "Add to whitelist".

![2022-12-01_22-32](https://user-images.githubusercontent.com/5488003/205163612-82daf1e2-4236-4a99-93a6-e088398d3362.png)

**Comment by anpic** [comment]
> PCAPdroid provides a default whitelist to avoid essential services disruption

It seems to me that we really need the same firewall setup via intents.
So that can customize all lists on your own ;)

**Comment by emanuele-f** [comment]
>It seems to me that we really need the same firewall setup via intents.
So that can customize all lists on your own ;)

Overkill for now, importing a list it's a one time operation. You can use the attached [hosts.html](https://github.com/emanuele-f/PCAPdroid/files/13707138/hosts.zip) page to convert standard hosts formats to the PCAPdroid one (conveniently hosted to https://pcapdroid.org/hosts.html)

**Comment by anpic** [comment]
> Overkill for now, importing a list it's a one time operation

This is primarily about other lists: about app block and white lists.
