### ISSUE TITLE
I need your telegram contact

### ISSUE THREAD

**Issue by fauziarnol** [emanuele-f/PCAPdroid#235]
I need your telegram contact

**Comment by emanuele-f** [comment]
This issue is spam. My email address is reported in the app about page

**Comment by fauziarnol** [comment]
https://youtu.be/HFcxV47bEq8

**Comment by fauziarnol** [comment]
hi mr emanuele . how can pcapdroid be added features like WPE PRO has?

Pada tanggal Kam, 14 Jul 2022 17.55, fauzi arnol ***@***.***>
menulis:

**Comment by emanuele-f** [comment]
It is open source, anyone can contribute. To get a chance for a feature to be implemented officially, you have to provide a detailed description of such feature.  At the current state, is not yet clear what you are asking to implement. Without it, there is nothing to discuss

**Comment by fauziarnol** [comment]
the feature i mean is.. when pcapdroid catches the . can we replay the
package sent? .. for example like a slot game .. can we replay the request
package as we wish .. please add a feature like that in pcapdroid .. this
is the example link I mean .. https://youtu.be/HFcxV47bEq8

Pada tanggal Sab, 16 Jul 2022 19.18, Emanuele Faranda <
***@***.***> menulis:

**Comment by fauziarnol** [comment]
hay sir emanuele .. how about my request about adding features like that of
WPE PRO ?

Pada tanggal Sab, 16 Jul 2022 23.25, fauzi arnol ***@***.***>
menulis:
