### ISSUE TITLE
SIPS over 443 causes an error

### ISSUE THREAD

**Issue by Rhynorater** [emanuele-f/PCAPdroid#238]
I'm trying to sniff traffic for the SIPS protocol (SIP over SSL) on port 443. It seems that MITMDUMP is thinking that this is HTTP and is returning a 400 Bad Request:
```
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: sip_transport.  Error processing 312 bytes packet from TLS x.x.x.x:443 : PJSIP syntax error exception when parsing 'Request Line' header on line 1 col 5:
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: HTTP/1.1 400 Bad Request^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: Server: mitmproxy 8.0.0^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: Connection: close^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: Content-Type: text/html^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: content-length: 194^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: ^M
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: <html>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: <head>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter:     <title>400 Bad Request</title>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: </head>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: <body>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter:     <h1>400 Bad Request</h1>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter:     <p>Bad HTTP request line: b&#x27;REGISTER sips:domain.com SIP/2.0&#x27;</p>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: </body>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: </html>
07-30 02:23:35.160  4417  5158 W PjsipLogWriter: -- end of packet.
```
What you see above is the `logcat` output from the app that is using SIP. It is logging that the `mitmproxy` is messing up the connection. I patched the mitm addon apk file to add the `--rawtcp` parameter to mitmdump, but it still doesn't play nice. Do you have any recommendations? This is one of the only working tools right now from bumping SSL for non-http protocols on Android.

Thanks,
Justin

**Comment by emanuele-f** [comment]
Hi, I don't have specific knowledge abiut this. I would start by checking if the latest mitmproxy release is able to proxy/decrypt it correctly. You can do this by following tbe instructions at https://emanuele-f.github.io/PCAPdroid/tls_decryption#35-decrypting-via-an-external-mitmproxy and setting up mitmproxy on your pc.

If this still does not work, you can tey asking on the mitmproxy issue tracker. Let me know if there is some missing option, it may be a good idea to allow users to specify additional mitmp4oxy options from the PCAPdroid app.
