### ISSUE TITLE
Migrate to Android JetPack Compose? from Android Views

### ISSUE THREAD

**Issue by correabuscar** [emanuele-f/PCAPdroid#239]
My understanding is limited as I'm only now learning Android, the Compose variant, but as PCAPdroid has `minSdkVersion 21`, I was just wondering if there's any chance you might consider migrating from Android Views to JetPack Compose ?

That being said, it's probably a ton of work(and I'm sure you're already working all the time and thus may not want any extra (especially unnecessary) work)

Although, they do say:
> Compose and the View system can work together side by side.

**Comment by emanuele-f** [comment]
What are the benefits of such a framework? Do you have a comparison of some code snippet before/after migration? Unless there are major advantages for future development, I would avoid rewriting existing code and instead focus on new features

**Comment by correabuscar** [comment]
It might take a while(months?) but I'll get back to you on that.

**Comment by emanuele-f** [comment]
Closing for now, please reopen when more info is available
