### ISSUE TITLE
Add ability to save the PCAP locally

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#24]
The app should implement a new dump mode to save the PCAP on the device storage.

**Comment by RedxTar** [comment]
I follow this motion

**Comment by emanuele-f** [comment]
This is now implemented in the dev branch. It will be available in the next release.

**Comment by emanuele-f** [comment]
If you want to test the new functionality before the official release, you can use [PCAPdroid-debug-76d422e.apk](https://github.com/emanuele-f/PCAPdroid/blob/debug-apks/PCAPdroid-debug-76d422e.apk)

Note: this is a debug apk, you need to uninstall PCAPdroid in order to switch between this and the official release apk.
