### ISSUE TITLE
App detection

### ISSUE THREAD

**Issue by chromer030** [emanuele-f/PCAPdroid#242]
Some apps detect PCAPdroid and doesn't word when it's installed and even it's not running and it's just installed , a workaround should be implemented to prevent this kind of detections.

One of apps are : [http injector](https://play.google.com/store/apps/details?id=com.evozi.injector&hl=en&gl=US)
![Screenshot_20f9](https://user-images.githubusercontent.com/13361552/183014166-49a7c2bf-8225-43df-a805-a42cece1da6f.png)

**Comment by emanuele-f** [comment]
Android allows listing other installed apps via its API, there is no way to prevent this at the moment. The solution to prevent detection is to rebuild PCAPdroid with a different package name.
