### ISSUE TITLE
Block incoming or outgoing traffic only

### ISSUE THREAD

**Issue by mianaliasjad** [emanuele-f/PCAPdroid#246]
Hi,

A feature in the firewall that allows blocking only outgoing traffic or incoming traffic individually. Is it doable?

**Comment by emanuele-f** [comment]
Hi, can you explain in which context it could be useful? I would just turn off mobile/wifi data all together

**Comment by mianaliasjad** [comment]
What if user don't trust some app and they want to block their outdoing traffic but allow incoming traffic.

**Comment by emanuele-f** [comment]
In this case he could just block the whole app (PCAPdroid supports this via its paid Firewall feature). Also note that in practice connections over the Internet are always outgoing as devices are under NAT and PCAPdroid only monitors outgoing connections without root

**Comment by emanuele-f** [comment]
Closing this issue as no practical use-cases has been spotted. Please reopen if you have other insights
