### ISSUE TITLE
how to parse pcap with app name?

### ISSUE THREAD

**Issue by eyalho** [emanuele-f/PCAPdroid#251]
Hey,
I use tshark on the recorded Pcaps and parse each session into some CSV.
I would like to add for each session information about the application source (and any other information about actions that occurred -are there more? like "open app screen" or extra events...).

How can I parse the Pcap so the information would be available? can tshark do that?

TNX in advance,
The PCAPdroid is pretty awesome :)

**Comment by emanuele-f** [comment]
This has been replied on telegram, please avoid double posting. Extra events like user interaction with the device are out of the scope of the pcapdroid app, but there should be an Android api to extract these (e.g. accessibility services)
