### ISSUE TITLE
Save log result to Database

### ISSUE THREAD

**Issue by unsa1nted** [emanuele-f/PCAPdroid#252]
Hi emanuele,

I hope you're in great condition. I have a question, how i can save the result log after started the traffic to database? as i see in the app there is save as .csv , but i need after i started the traffic then logged to my database (mysql).

Which one code that i can connect & save it to database?

Thank you!

**Comment by emanuele-f** [comment]
Hi, I think you have two options.
1. modify PCAPdroid to connect to your db and export the metadata you need
2. use the [PCAPdroid API](https://github.com/emanuele-f/PCAPdroid/blob/master/docs/app_api.md) to configure PCAPdroid to send the pcap file to your app (udp exporter mode) and process the traffic there

In both cases you will need to code your logic. If you are interested in my consulting, please contact me via email

**Comment by unsa1nted** [comment]
Hi, Thank you for your response Emanuele, i have send an email to you.

Thank you!

**Comment by emanuele-f** [comment]
Replied via email
