### ISSUE TITLE
can not see redundant packet  in dump file

### ISSUE THREAD

**Issue by weibo19830307** [emanuele-f/PCAPdroid#256]
hello,  i have use PCAPdroid to capture the network packet in weak signal environment, but in dump file there is no any retransmited packets and duplicate ack packets? is the PCAPdroid filtered the retransmited packets? looking forward to your reply,thanks!

**Comment by emanuele-f** [comment]
Please check out https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis . In short, you need to enable the root capture on a rooted device

**Comment by weibo19830307** [comment]
@emanuele-f ,Thank for your reply.

**Comment by emanuele-f** [comment]
You are welcome
