### ISSUE TITLE
Add ability to block quic in non-decryption mode

### ISSUE THREAD

**Issue by kevino-techie** [emanuele-f/PCAPdroid#259]
Currently blocking of quic is available only when decryption is turned on. So a way to block any quic connections in normal capture mode would be insightful to see how an apps react to such blocking of one protocol. The expected behaviour for them is to switch to a TLS connection.

**Comment by emanuele-f** [comment]
I've made this issue more generic to be able to block arbitrary protocols, which may come useful for different use-cases

**Comment by ignoramous** [comment]
Rethink copied this list over from `iana.org` which might come in handy here: https://github.com/celzero/rethink-app/blob/0e2339d38317145070747b3ed8891cdca8c25aea/app/src/main/java/com/celzero/bravedns/util/KnownPorts.kt
