### ISSUE TITLE
Certificate not trusted

### ISSUE THREAD

**Issue by JitongZ** [emanuele-f/PCAPdroid#262]
I have a question while using the app.
Here is the error message when trying to decrypt the package from an app.
`The client does not trust the proxy's certificate for <some url here> (OpenSSL Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert certificate unknown')]))`
Is there a way to solve this? I have installed the CA certificate but it seems to be rejected.

Thank you!

**Comment by emanuele-f** [comment]
Android implements a number of security protections which need to be bypassed with specific techniques. This is discussed in depth in the user guide https://emanuele-f.github.io/PCAPdroid/tls_decryption . My suggestion is to try to decrypt chrome first, then move to other apps by following the techniques highlighted in the user guide
