### ISSUE TITLE
Selective whitelist for TLS decryption

### ISSUE THREAD

**Issue by yoshimo** [emanuele-f/PCAPdroid#266]
Android applications pull in various third-party components like SDKs for advertising, bugreporting, database operations and more.
Certificate pinning is not always used for every host contacted  and not by every application.

There should be an option to target every application for decryption  BUT certain combinations of app and contacted domain.
If PCAPdroid finds that connections can't be decrypted because the certificate isn't trusted , it could add this host:app combination to a list from which you can enable/disable list entries to exempt them from decryption.
So you get most traffic in the clear while not breaking applications.

**Comment by kevino-techie** [comment]
Selective/multiple apps selection/whitelisting should be added to socks5 proxy mode as well. It can have various uses cases for ex . when using decryption on external device on selective apps could be proxied.

**Comment by emanuele-f** [comment]
An untrusted certificate warning should be reviewed by the user, as it could mean that the certificate is not properly installed or that certificate transparency is in use, so I'm removing the "automatic" part from this issue.

Currently in PCAPdroid you can only whitelist a domain or an app, but not the combination of the two, and I think this is enough for this issue. In essence for this issue we need:

1. a whilelist for decryption which can be changed while the capture is running, in the left drawer
2. connections context menu actions to whitelist app/domain

**Comment by emanuele-f** [comment]
> Selective/multiple apps selection/whitelisting should be added to socks5 proxy mode as well

Please open a separate issue and explain the use-case in more detail
