### ISSUE TITLE
Ability to log all the connections

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#27]
Currently the app only shows the active connections. It would be great to add an option to record and show all the connections since the app start.

- [x] Retain all the connections until app is stopped
- [x] Ability to filter the connections by app
- [x] Improve app layout
- [x] Ability to export the connections log

Ongoing development on the [dev branch](https://github.com/emanuele-f/PCAPdroid/commits/dev). The new features can be tested by installing the [PCAPdroid-debug-dc08b8a.apk](https://github.com/emanuele-f/PCAPdroid/blob/debug-apks/PCAPdroid-debug-dc08b8a.apk).
Note: this is a debug apk, you need to uninstall PCAPdroid in order to switch between this and the official release apk.

This is how the new app looks like:

<p align="center">
<img src="https://user-images.githubusercontent.com/5488003/108608515-a17de280-73c7-11eb-9c75-ee8c1b0b98f1.jpg" width="200" />
<img src="https://user-images.githubusercontent.com/5488003/108608513-a04cb580-73c7-11eb-9590-a86475516f9f.jpg" width="200" />
</p>

- The apps tab shows a grouped view of the connections by app (indicated in parenthesis)
- By clicking on an app, it is applied as a filter and the connections tab is shown
- The app filter can be removed by simply tapping on the app icon in the action bar
- The connections tab now logs all the connections since the app start. There is a limit of 4192 max connections, after which the old ones will be discarded.
- By clicking on the "fab down" icon its possible to scroll the connections view to the bottom and autoscroll on new connections

As the next step, I'm willing to improve the overall layout. The tabs in the `ViewPager` do not look good and scrolling is not perfect as the pager sometimes catches the scroll of the recyclerviews. Maybe the app tab should become a separate activity and menu should be reorganized in [navigation drawer](https://material.io/components/navigation-drawer).

[update]

Navigation drawer now implemented. The apps and connections views have been moved to the new `Inspector` activity. This clearly divides the capture data from the in-memory analysis. Changes can be tested via the [PCAPdroid-debug-e5a7748.apk](https://github.com/emanuele-f/PCAPdroid/blob/debug-apks/PCAPdroid-debug-e5a7748.apk)

<p align="center">
<img src="https://user-images.githubusercontent.com/5488003/109415050-a853b900-79b6-11eb-983b-81bef11e3998.jpg" width="200" />
</p>

[update 2]

The connections export (in CSV format) is now implemented. The connections tab has been brought back to the main activity to simplify interaction and a new `Apps` has been created. Changes can be tested via the [PCAPdroid-debug-e5a7748.apk](https://github.com/emanuele-f/PCAPdroid/blob/debug-apks/PCAPdroid-debug-b31975c.apk).

**Comment by arf88** [comment]
Yes please, also ability to retain the connection information until you hit stop. I created a new Issue #28 to further explain. Thanks again for your hard work

**Comment by decodering22** [comment]
Will install and do some testing thanks

**Comment by decodering22** [comment]
Hi Emanuele, a few things to point out.

The ability to see the App tab is great but I'm unsure if the filter is working as it appears to be logging all connections despite selecting an individual app to filter. Not sure if this is by design or not? 

If for example you want to filter to a specific app and I know because I tested this with released version, the status shows the KB it logs and it is very consistent. With the beta it appears to log everything even though I filtered to just the app in question.

This is actually not a bad thing, I like that I can see the OS and system apps and how they are also interacting when it is logging, but it would be helpful possibly before you export to select what data you want to export specifically so it is easier to see the data in wireshark specific to the filtered app or other system and OS processes as well. 

In regards to HTTP Server, it is behaving like the last release in Play. 
If i click on the link in the app firefox opens and it is indefinitely downloading and stuck at 0%.
If i open the url in a browser on my PC it says Unknown time left and it appears to keep downloading indefinitely.

**Comment by decodering22** [comment]
To update my feedback:

As far as the download, this is what appears to be working. Both on the phone and web browser

Click on the link in the app or open a browser on the pc and put in the link and it will continue to show as if it is downloading and remain a 0%, but when you stop the trace on the app, it will download the file size matches. This actually makes sense as you keep the app running the more data is collected it will grow the log.

Really the only thing I would like to see is if you are not filtering anything but later decide to filter to a specific app while it is recording, if it is possible when you export the data to only export the app you filter to. I don't think this is possible.

**Comment by emanuele-f** [comment]
> Hi Emanuele, a few things to point out.
> 
> The ability to see the App tab is great but I'm unsure if the filter is working as it appears to be logging all connections despite selecting an individual app to filter. Not sure if this is by design or not?
> 

As of the email follow up, the `netd` app could appear when a filter is selected.

> If for example you want to filter to a specific app and I know because I tested this with released version, the status shows the KB it logs and it is very consistent. With the beta it appears to log everything even though I filtered to just the app in question.
> 

Agree on the fact that these inconsistencies are bad. Will fix as a part of the gui layout rework.

> This is actually not a bad thing, I like that I can see the OS and system apps and how they are also interacting when it is logging, but it would be helpful possibly before you export to select what data you want to export specifically so it is easier to see the data in wireshark specific to the filtered app or other system and OS processes as well.
> 

It is better to integrate the app info inside the exported data, see #36
