### ISSUE TITLE
[Feature Request] Add option to choose the dns server in case fallback

### ISSUE THREAD

**Issue by johnexu** [emanuele-f/PCAPdroid#275]
The dns server by default in case fallback is google.

send information to google even more without having a second option is not compatible with a security and privacy app.

let a more privacy friendly as standard for users who will not be careful to observe this, such as aha u quad9, among others who have no-logs policy.

and add beyond the set by default others for users to choose.

**Comment by karano-techie** [comment]
one more reason to change dns server  from googles one is because it doesn't support dnssec. 

Also i am not sure if the current proxy fallback dns requesrs are made on dot or in plaintext.
