### ISSUE TITLE
Change order of connections in the dashboard

### ISSUE THREAD

**Issue by johnexu** [emanuele-f/PCAPdroid#276]
to see the latest connections you need to click the button with arrow down.

in most of the traffic analysis and firewall apps the latest connections are always at the top without needing the user to click another button to view, and this makes the use more practical and comfortable. and I think most users are familiar like this.

then change ordering to a default format like other similar apps

**Comment by karano-techie** [comment]
its a user preference honestly. But new connections on bottom are more standard in my opinion. For example wireshark shows new connections on bottom.
There is 'jump to bottom' button , which makes it easy to get to the newest connection.

**Comment by emanuele-f** [comment]
Yeah, log-like network monitoring tools like wireshark usually show the latest connections at the bottom. For other tools which show a *snapshot* of the active state (e.g. `top`, showing the active processes) it's common to see the most relevant items at the top. I think the current implementation is ok and right now I prefer to avoid more complexity to support this kind of feature. Closing for now
