### ISSUE TITLE
Connections retention option

### ISSUE THREAD

**Issue by arf88** [emanuele-f/PCAPdroid#28]
Hi, not a bug more of a request. When filtering an app to keep the information in the Connections tab until you stop. The problem with taking the pcap file to wireshark is that it does not resolve the ip to a DNS name, it takes time to check every IP. In the Connections tab it does tell you at a quick glace what destination it was sending data to, however after about 30 seconds the information in the connections tab disappears. I would really like to know if there is a way to keep it there until you hit the stop button? 

Thanks and thanks for creating this very useful app

**Comment by emanuele-f** [comment]
Thanks for the feedback. This is part of #27 .
