### ISSUE TITLE
APP crashes when importing huge .json file with blocked hosts.

### ISSUE THREAD

**Issue by rtkpX** [emanuele-f/PCAPdroid#284]
.json file generated with https://pcapdroid.org/hosts.html

.json file used: https://usaupload.com/6OvM/PCAPDROID_BLOCK.json

raw blocked hosts: https://usaupload.com/6OvL/raw_blocked_hosts.txt

Basically, after all that, when importing the file, the app will just crash.

Edit: BTW, phone has 12GB of RAM (Realme GT NEO 2 12GB-256GB)

**Comment by emanuele-f** [comment]
The latest fix allows loading big blacklists, but the UI gets stuck at some points (e.g. while starting the capture).
This should either be fixed or a limit in the number of rules should be added.
