### ISSUE TITLE
Send decrypted data via Intent

### ISSUE THREAD

**Issue by mrleadhead** [emanuele-f/PCAPdroid#286]
Hi, 

I think it would be a great feature if one of the dump options was to send the decrypted http data in plain text via an intent. This would allow this app and the data extracted to be used in a automation tool such as tasker.

**Comment by emanuele-f** [comment]
What kind of processing you wish to perform with tasker? Can you share some code regarding your implementation so far, in particular regarding the intent-based communication with tasker? Please note that the PCAP that you receive in UDP dump mode is still encrypted.
What about dumping the traffic to a PCAP file, then feeding the pcap and the keylog to tshark for decryption? Please also note that the beta version of PCAPdroid [accepts custom mitmproxy options](https://github.com/emanuele-f/PCAPdroid/issues/283), so there may be some option to dump the requests to file.

**Comment by mrleadhead** [comment]
I want to read the json response data and when I see a certain value, flash a message on screen, preferably this will all be done on the device and in "real time" so Tshark won't work in this case. Unfortunately the app I am using for the intent based communication is not open source [Google play](https://play.google.com/store/apps/details?id=com.whitedavidp.udplistenerfortasker&hl=en_GB&gl=US). 

However, what I had in mind was something like,
For each http TX/RX pair:
```
Intent intent = new Intent();
intent.setAction("com.example.broadcast");
intent.putExtra("ReqURL", foo.url);
intent.putExtra("Reqbody", foo.body); //for Post requests
intent.putExtra("Reqheader", foo.header);
intent.putExtra("Resbody", bar.body ); 
intent.putExtra("Resheaders", bar.header); 
sendBroadcast(intent);
```

Might want to consider not making this a broadcast, but not sure how that would work at the moment. 
A filter to limit what gets sent as an intent would be useful as well. 

I understand this will likely be a lot of effort to implement and it's fair for the core functions of this app. So it's ok if you don't want to. 

I took a look at implementing something myself unfortunately my Java is poor and I have not done Android development before. But I will take aother look and let you know if I make any progress.

**Comment by emanuele-f** [comment]
> I want to read the json response data and when I see a certain value, flash a message on screen

If you are going to modify PCAPdroid, then you could probably match data and display such a dialog from PCAPdroid itself, without tasker

> Might want to consider not making this a broadcast, but not sure how that would work at the moment

According to the Tasker docs, broadcasts seem to be the supported way to interact with it

> I understand this will likely be a lot of effort to implement and it's far from the core functions of this app

Yeah, this seems to only solve a very specific problem. For this kind of stuff I prefer to give people the ability to integrate with the app [via its api](https://github.com/emanuele-f/PCAPdroid/blob/master/docs/app_api.md). But integrating with the API still requires programming.

> I took a look at implementing something myself unfortunately my Java is poor and I have not done Android development before.

If you have some programming experience, you should be able to install Android studio and build the app quite easily, check out the [build instructions](https://github.com/emanuele-f/PCAPdroid/#building). [This is the line](https://github.com/emanuele-f/PCAPdroid/blob/85e1ceb88ee4e1fb6e2b2045f797cebf9c9b06a5/app/src/main/java/com/emanuelef/remote_capture/MitmReceiver.java#L316) in which decrypted data is added to the connection.

**Comment by mrleadhead** [comment]
Thanks for the help. I have managed to build and deploy the app, I was stuggling with my subpar Java knowledge to work out where decrypted data is added to the connection. Now I know I should be able to scrape together what I need.
