### ISSUE TITLE
Why i need to reopen a blocked app from firewall to get back the internet access?

### ISSUE THREAD

**Issue by mianaliasjad** [emanuele-f/PCAPdroid#290]
Hi,

Let's suppose I have added "Chrome" app in the firewall blocklist.
1) Go to chrome and check if it has internet access. No it does not.
2) I go back by keeping the chrome app in recents to PCAPdroid app and delete chrome from firewall blacklist
3) Go back to chrome from recent and check if it has internet access. unfortunately it does not. we have to remove chrome from recent app completely and reopen it to get internet access.

Is it correct behavior? Thanks

**Comment by emanuele-f** [comment]
PCAPdroid unblocks active connections, but chrome "remembers" that it had no internet access for some time. You will either need to wait until it checks for connectivity again or swipe from recent apps
