### ISSUE TITLE
Some apps refuses to open if PCAPdroid is installed.

### ISSUE THREAD

**Issue by skj-skj** [emanuele-f/PCAPdroid#291]
Hi I am seeing one app which check for PCAPdroid package name in the phone and refuses to open and prompt to uninstall pcapdroid to open the app.

I renamed the package name and that app open without any issue, but renaming package name makes the app unstable.

if you can add apk with different package name in the assets it will be helpful. but I also didn't expect you to create whole new build pipline just for my need, if it possible please add it to your backlog else close this issue.

Thanks.

**Comment by kevino-techie** [comment]
Can you try installing the beta version of the app.It may solve the problem. The beta repo of the app is https://pcapdroid.org/fdroid/repo

**Comment by emanuele-f** [comment]
You should report such an app to Google Play, as the app is probably abusing its package visibility permissions, or contact that app developers. It's not something that we can solve in PCAPdroid, as the package would be blocked again once it becomes popular. The correct way to change the package name is to rebuild the app from source with a different id. That creates no issues.

**Comment by skj-skj** [comment]
thx for your response. I will try to rebuild the app.
