### ISSUE TITLE
Prefer MIT / Apache icons 

### ISSUE THREAD

**Issue by ignoramous** [emanuele-f/PCAPdroid#292]
Hi there,

You can consider searching for permissively licensed icons from [IconDuck](https://iconduck.com). Highly recommended especially given the high quality and garden variety of icons available there. 

Using proprietary or icons with onerous licenses is fine, but it could be avoided.

For our app, we maintain a list of icons we source in a single webpage ([ex](https://github.com/celzero/rethink-app/issues/346)) and link to it from the app for attribution purposes.

**Comment by emanuele-f** [comment]
Hi, thanks for your suggestion. I will look how these icons looks like, icons license is not an issue unless they have a restrictive license.

**Comment by emanuele-f** [comment]
It seems like most if not all the icons that we have could be migrated to IconDuck, but again I'm not concerned about icon license as long as I can redistribute them in the app without limitations (which is the case), so I will keep the current icons for now. Closing this

**Comment by ignoramous** [comment]
You can't really know if you can sell what you've built when the licenses are laced with non-commercial clauses: https://github.com/emanuele-f/PCAPdroid/tree/playstore/ICONS_LICENSE

Not a lawyer, but one license in there looks incompatible with GPLv3 (which means, this repo itself cannot really be licensed with GPLv3).

ymmv
