### ISSUE TITLE
can VPN does not modify report text fields?

### ISSUE THREAD

**Issue by xullent** [emanuele-f/PCAPdroid#299]
can VPN does not modify agreement fields?

**Comment by emanuele-f** [comment]
Please explain what you mean. The Pcapdroid app cannot modify the traffic, only block it

**Comment by xullent** [comment]
![image](https://user-images.githubusercontent.com/24709841/218908418-1c604f0c-b466-4015-9187-d082e71785ee.png)
The Identification id is zero , is the PCAPdroid app modify it?

**Comment by emanuele-f** [comment]
If you are using Vpn mode then yes, all packets from the internet have synthetic IP, TCP, UDP and ICMP headers, see https://emanuele-f.github.io/PCAPdroid/quick_start#14-packet-analysis . If you want a real view on the traffic, you need root
