### ISSUE TITLE
How do i specify port in ip address?

### ISSUE THREAD

**Issue by mianaliasjad** [emanuele-f/PCAPdroid#300]
I want to block a specific port of an ip address. How do i specify that port? In firewall.

**Comment by emanuele-f** [comment]
Hi, this is currently not supported. Can you explain more about your use case?

**Comment by mianaliasjad** [comment]
There is an app on the play store that allows to block ip address with specific port also. Not only that but it also allows using wildcards while defining rules for ip address in firewall. If that feature can be included in this app then it would be awesome.

here is app: https://play.google.com/store/apps/details?id=app.greyshirts.firewall

![image](https://user-images.githubusercontent.com/31348542/219605765-f4b2621c-cd56-4dc5-bdcc-1681588aad91.png)

**Comment by emanuele-f** [comment]
Wildcard subdomain matching is already implemented in PCAPdroid, it's just implicit. Here is an extract from the [firewall docs](https://emanuele-f.github.io/PCAPdroid/paid_features#51-firewall):

_Blocking a second-level domain like example.org will cause all of its subdomains to be blocked (e.g. some.example.org and img.example.org). This only applies to second-level domains, so blocking another.example.org will not block yet.another.example.org._

I cannot find good use cases for port-based blocking on mobile devices, no plan to implement this in the near future
