### ISSUE TITLE
Could "Google Backup Transport" be innacurate/something else?

### ISSUE THREAD

**Issue by ForestCat4** [emanuele-f/PCAPdroid#303]
Hi,
Samsung touchwiz Android 6.01 ROM, rooted / Magisk

I have frozen/killed/force-stopped, etc.  Google Backup Transport(com.google.android.backuptransport) in SD Maid.  After multiple reboots, the app is still showing frozen/disabled/etc in SD Maid, Titanium, and even the Android App manager.
I can't see it in ps output from adb shell.
HOWEVER---
PCAPDroid is showing 'Google Backup Transport' with active connections, w/ uid 10013
In App details, if I click the gear, it takes me to the App manager page for Google Backup Transport, and it shows as stopped/disabled, no memory usage.

In logcat (adb as root):
=== no references to "backup transport" other than:
03-09 11:39:26.312 25188 27330 D pcapdroid-native: [TCP4] 10.215.173.1:35517 -> 142.251.163.188:5228 [10013/Google Backup Transport]

=== no references to "10013" other than:
03-09 11:37:28.292  1474  4040 D NetworkPolicy: isUidForegroundLocked: 10013, mScreenOn: false, uidstate: 6, mProxSensorScreenOff: false

03-09 11:26:40.752  1474  4450 D WifiService: startScan by pid=5015, uid=10013

03-09 11:27:37.662   559  2666 D Netd    : getNetworkForDns: using netid 504 for uid 10013

03-09 11:38:44.822  1474  4096 D ConnectivityService: unneeded: NetworkRequestInfo for = Listen from uid/pid:10013/5015 for NetworkRequest [ id=33, legacyType=-1, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]

In a ps output (from adb shell as root):
the only reference to pid 5015 (see above) is com.google.android.gms

How are you determining that uid 10013 is Google Backup Transport?

Is there some way to get more detailed process/package info from PCAPDroid?

Thanks

**Comment by emanuele-f** [comment]
Hi, in Android packages can share the same uid, which allows them to share data between them more easily. This practice is discouraged, but often used by system apps. So here it seems like the uid 10013 is mapped to multiple package names. Pcapdroid can only determine the uid of a connection, so it will show only one package for it (the first in alphabetical order)

**Comment by emanuele-f** [comment]
No feedback received, closing
