### ISSUE TITLE
Add authentication in Socks5 proxy

### ISSUE THREAD

**Issue by nnnlog** [emanuele-f/PCAPdroid#304]
MITMProxy provides socks5 proxy authentication like belows.
```bash
mitmweb --mode socks5 --listen-port 8050 --proxyauth username:password
```

However, there is not socks5 proxy authentication setting in PCAPdroid. The app don't use authentication option. (https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L376)

Is there any plan to add authentication option?

**Comment by emanuele-f** [comment]
This is already implemented for the built-in mitmproxy, I just need to expose it to the ui

**Comment by emanuele-f** [comment]
This will be available in the next release. You can test it with [this beta apk](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.1-8e584fa.apk)
