### ISSUE TITLE
Vivo link no good

### ISSUE THREAD

**Issue by jidanni** [emanuele-f/PCAPdroid#308]
In https://emanuele-f.github.io/PCAPdroid/tls_decryption and
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/fragments/mitmwizard/InstallCertificate.java there is a [link to vivo](https://www.vivo.com/en/support/questionByTitle?title=How%20to%20turn%20on/off%20Autostart%20for%20my%20apps) which just gives
> Sorry , no content related to "How to turn on/off Autostart for my apps" .

**Comment by emanuele-f** [comment]
Thanks for reporting. Link updated
