### ISSUE TITLE
Show when we change to running mode more clearly

### ISSUE THREAD

**Issue by jidanni** [emanuele-f/PCAPdroid#309]
Below the big circle in the app, in fine print, one sees,
- TLS decryption is starting

After a while, this changes to an equally small
- TLS decryption is running

I say there should be a giant green check mark, ~~or spinner~~ or something, in the middle of the screen,
that shows up and stays there, starting when the second message is printed.

**Comment by emanuele-f** [comment]
The status view shows different things (capture running, HTTP server port, root capture interface), and the TLS decryption mode is just one of them. The challenge is supporting different modes and still provide a consistent look. There are many things to improve in the PCAPdroid UI, but this is low priority for me, as there are other important things to do first.
If possible, please provide a pull request to improve the layout and I will review it. If not, this will be a won't fix
