### ISSUE TITLE
Ability to add host URLs to firewall and malware areas 

### ISSUE THREAD

**Issue by xxxsskxxx** [emanuele-f/PCAPdroid#311]
Hi

Great app! 

This is an enhancement ask to allow the user to be able to add URL hosts to act as a blacklist within the malware or firewall areas (not sure where this would sit better)

What I would like to do is add the list of host's from here:

https://divested.dev/hosts

To my firewall blacklist as a 'URL', we currently have the app, host and IP Address options. The 'URL' would act as an additional option in this menu.

Thanks

**Comment by emanuele-f** [comment]
Hi, there are some implications of providing such a feature, please check out https://github.com/emanuele-f/PCAPdroid/issues/207#issuecomment-1352862928 .
There is no plan to implement this for the time being. As a workaround, you can use the import JSON rules feature and the https://pcapdroid.org/hosts.html script to convert standard hosts lists into the JSON supported by PCAPdroid. Beware that loading a high number of rules will produce a slowdown in some app activities.
