### ISSUE TITLE
about changing Source IP address

### ISSUE THREAD

**Issue by testerjy** [emanuele-f/PCAPdroid#323]
Can I change the source ip address used for VPN connections?
Even if it's manual

because everytime pcapdroid use same source ip even change moblile

**Comment by emanuele-f** [comment]
This ip address is only used to route traffic inside your Android device. On the LAN/WAN your real ip will be used

**Comment by testerjy** [comment]
Thank you for your kind explanation.

However, I wanted to know if there would be an option to distinguish between terminals by just looking at packet messages when I got a pcap file using an app on more than two mobiles.

In reality, we will use real ip, but it is difficult to distinguish which mobile these packet messages came from when looking at the pcap file.

Is there any other way besides changing the file title to distinguish it?

**Comment by emanuele-f** [comment]
Using the file name seems a good solution. If you want to change the vpn ip address you will need to modify the source and rebuild the app

**Comment by testerjy** [comment]
I understand.
thank you for help
