### ISSUE TITLE
No SSLKeyLog file in HTTP server mode after capture stopped due to low memory

### ISSUE THREAD

**Issue by n-aggarwal** [emanuele-f/PCAPdroid#324]
I was running a long PCAP capture on the HTTP server mode and the data was being captured in Wireshark. Unfortunately, my capture stopped due to low memory (I did have full payload toggled). The issue is that when I opened the app after seeing the message I was unable to find/download the SSLKeyLog file that is used to decrypt the data. As a result, I can't decrypt the packets in Wireshark.

**Comment by emanuele-f** [comment]
When terminated abnormally, PCAPdroid will now prompt to save the KEYLOG on next app start. For better support and usability, please consider buying the [PCAPNG format support](https://emanuele-f.github.io/PCAPdroid/paid_features#53-pcapng-format).

**Comment by n-aggarwal** [comment]
Thank you!
