### ISSUE TITLE
LineageOS 19.1: unwanted GPS pings upon PCAP start

### ISSUE THREAD

**Issue by dob777** [emanuele-f/PCAPdroid#328]
Hi there!

I am experiencing strange behaviour of my phone when listening network communication using PCAPdroid.
When I start listening 2 "GPS" connections pop up right away: one `TCP,7275` port and second `DNS,53`. As well as these GPS ping happen several times a day when I listen. See the screenshot:

<img src="https://github.com/emanuele-f/PCAPdroid/assets/121567421/fde6f76e-29d4-4f9f-bdf7-2901bf62b504" width="300" />

So I am wondering whether this is PCAPdroid's feature or my phone/OS feature?
I'd like to make sure that my phone don't make unwanted connections at all, like super-clean-privacy.

So I'll appreciate any hints here and thank you for your answers in advance.

extra:
I am not android-savvy but I tried to "`logcat | grep GPS`" using adb shell and found following lines:
```
06-14 19:26:35.531  8369 10133 D pcapdroid-native: [TCP4] 10.215.173.1:36492 -> 3.219.146.176:7275 [1021/GPS
06-14 19:26:35.533  8369 10133 D pcapdroid-native: [UDP4] 10.215.173.1:54292 -> 10.215.173.2:53 [1021/GPS]
```
I have no idea what those two lines means exactly but they seem to belong to pcapdroid so I decided to ask you directly.

**Comment by emanuele-f** [comment]
Hello, these lines in the log are logged by PCAPdroid itself. For any connection you see in the UI, you will see a log line as well.
These connections are generated by the system GPS app. They are probably related to [A-GPS](https://en.wikipedia.org/wiki/Assisted_GNSS), which uses the internet to speed up GPS positioning. Privacy-wise, I don't have many information on this, but this seems like a core feature of the Android device, so blocking it may cause some problems (e.g. inability/slowed down retrieval of GPS position). To block this or similar connections from system apps, you can use the PCAPdroid [firewall feature](https://emanuele-f.github.io/PCAPdroid/paid_features#51-firewall) (paid).

**Comment by dob777** [comment]
thank you very much for the comprehensive answer

**Comment by emanuele-f** [comment]
You are welcome! Feel free to ask any question here or on telegram/matrix

**Comment by emanuele-f** [comment]
On PCAPdroid start, a VPNService is started, which triggers a connectivity change event (interfaces, routing tables and ip addresses changed). Apps can detect this event and react
