### ISSUE TITLE
Is it possible to specify a custom CA certificate & key pair for MitM?

### ISSUE THREAD

**Issue by shunf4** [emanuele-f/PCAPdroid#330]
I tried replacing files in `/data/data/com.pcapdroid.mitm/files/.mitmproxy` with no luck. There seems to be some verification mechanism, and the cert & key was immediately replaced by a new pair when I started capturing the network traffic.

**Comment by emanuele-f** [comment]
Please refer to the official mitmproxy docs: https://docs.mitmproxy.org/stable/concepts-certificates . The custom certificate should then be used by PCAPdroid

**Comment by shunf4** [comment]
I tried mitmproxy 9.0.1 and it sucessfully validated and used my CA cert:
```bash
$ sha256sum ./my-mitmproxy-ca/*
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  ./my-mitmproxy-ca/mitmproxy-ca-cert.cer
e63e535de50f411def905f73af5fbcb667db922b4ba1cbe75761f22e1763f0ae  ./my-mitmproxy-ca/mitmproxy-ca-cert.p12
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  ./my-mitmproxy-ca/mitmproxy-ca-cert.pem
6690a0ba4f300fc45e1df123bbd4a2471524eddc831997f28a21780f523ac9f1  ./my-mitmproxy-ca/mitmproxy-ca.p12
da84ce010757da36757ea8a95933e2cb58a2175cbddd819d4ade35d7d06d466a  ./my-mitmproxy-ca/mitmproxy-ca.pem
8a4d78a835f8e4f00cd9fa9abe6ef943704510fe5b9b37324e6e01881417d845  ./my-mitmproxy-ca/mitmproxy-dhparam.pem
$ ./mitmproxy --set confdir=./my-mitmproxy-ca
$ # mitmproxy successfully starts and shows TUI
$ sha256sum ./my-mitmproxy-ca/*
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  ./my-mitmproxy-ca/mitmproxy-ca-cert.cer
e63e535de50f411def905f73af5fbcb667db922b4ba1cbe75761f22e1763f0ae  ./my-mitmproxy-ca/mitmproxy-ca-cert.p12
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  ./my-mitmproxy-ca/mitmproxy-ca-cert.pem
6690a0ba4f300fc45e1df123bbd4a2471524eddc831997f28a21780f523ac9f1  ./my-mitmproxy-ca/mitmproxy-ca.p12
da84ce010757da36757ea8a95933e2cb58a2175cbddd819d4ade35d7d06d466a  ./my-mitmproxy-ca/mitmproxy-ca.pem
8a4d78a835f8e4f00cd9fa9abe6ef943704510fe5b9b37324e6e01881417d845  ./my-mitmproxy-ca/mitmproxy-dhparam.pem
$ # SHA256 of cert & key files not changed, the files are valid
$ ./mitmproxy --version
Mitmproxy: 9.0.1 binary
Python:    3.11.0
OpenSSL:   OpenSSL 3.0.7 1 Nov 2022
Platform:  Linux-5.4.0-148-generic-x86_64-with-glibc2.35
```

However, with the same files copied to phone, they were still replaced on PCAPdroid starts:
```
/data/data/com.pcapdroid.mitm/files/.mitmproxy # sha256sum *
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  mitmproxy-ca-cert.cer
e63e535de50f411def905f73af5fbcb667db922b4ba1cbe75761f22e1763f0ae  mitmproxy-ca-cert.p12
c3de11972e9a90877c20045e36ec997b35e70d269b9106c788d338bcb0eab1b1  mitmproxy-ca-cert.pem
6690a0ba4f300fc45e1df123bbd4a2471524eddc831997f28a21780f523ac9f1  mitmproxy-ca.p12
da84ce010757da36757ea8a95933e2cb58a2175cbddd819d4ade35d7d06d466a  mitmproxy-ca.pem
8a4d78a835f8e4f00cd9fa9abe6ef943704510fe5b9b37324e6e01881417d845  mitmproxy-dhparam.pem
/data/data/com.pcapdroid.mitm/files/.mitmproxy # # After switching on PCAPdroid
/data/data/com.pcapdroid.mitm/files/.mitmproxy # sha256sum *
83714bf471b5b0da8ebc6885531d38cab8ab5ebeec8b345073db2bc6fb8bfe76  mitmproxy-ca-cert.cer
fcb94b74589dddce0c743a2d08a863c198d9793a3b8971fa81ed8f74f13f5dc8  mitmproxy-ca-cert.p12
83714bf471b5b0da8ebc6885531d38cab8ab5ebeec8b345073db2bc6fb8bfe76  mitmproxy-ca-cert.pem
09ec3f9ad61148451cac07f305ff045a6d22ec441bb1ec3c4aef030771092959  mitmproxy-ca.p12
6bd06e02297af7fc661115c0d0135430eeaf3cd4e4be89152abcf3711c327660  mitmproxy-ca.pem
8a4d78a835f8e4f00cd9fa9abe6ef943704510fe5b9b37324e6e01881417d845  mitmproxy-dhparam.pem
/data/data/com.pcapdroid.mitm/files/.mitmproxy # # the cert & key is changed
```

**Comment by shunf4** [comment]
I tried adding `--set confdir=/path/to/dir` in "Additional mitmproxy options" in PCAPdroid's settings. PCAPdroid seems not using it; the issuer of server certificate is still "CN=PCAPdroid CA, O=PCAPdroid".

**Comment by shunf4** [comment]
Found that I'm not using latest PCAPdroid (v1.6.4), so I upgraded to v1.6.5 (and mitm plugin to v0.15).

Then TLS Decrypt stopped working...😂 the connections just no longer were MitM'ed. Will look into this later

**Comment by emanuele-f** [comment]
Oh I forgot about [this check](https://github.com/emanuele-f/PCAPdroid-mitm/blob/master/app/src/main/python/mitm.py#L164) on the CA common name, the CN must be "PCAPdroid CA".
Regarding v1.6.5, please note that decryption logic has changed, so you now need to configure "Decryption rules" to specify which apps to decrypt. Check out https://github.com/emanuele-f/PCAPdroid/releases/tag/v1.6.5 for the full changelog

**Comment by westruk** [comment]
> Oh I forgot about [this check](https://github.com/emanuele-f/PCAPdroid-mitm/blob/master/app/src/main/python/mitm.py#L164) on the CA common name, the CN must be "PCAPdroid CA".
> Regarding v1.6.5, please note that decryption logic has changed, so you now need to configure "Decryption rules" to specify which apps to decrypt. Check out https://github.com/emanuele-f/PCAPdroid/releases/tag/v1.6.5 for the full changelog

It's fixed in latest beta?
