### ISSUE TITLE
Newest version of mitm addon doesn't decrypt tls and https

### ISSUE THREAD

**Issue by TopGamerPro16** [emanuele-f/PCAPdroid#331]
There is a very large chance I'm wrong, but when i upgraded, which, I'm required by the PCAPdroid app to do so, i noticed the apps of which allow  user certificates stopped being decrypted by PCAPdroid. (An app i hand edited from apktool to accept user certificates and Samsung Internet)

It just says "Encrypted" next to the "Decryption" field of a connection. 

Keep in mind i only use pcapdroid every once in a while, and don't have explicit memory proof that this is what caused it. I cant say wether or not it would've worked worked in a previous version because PCAPdroid does not allow me to. Somehow, turning off wifi and clearing data has no effect. Last i used thd app was about a week ago, and the app worked perfectly, for the apps that allow the user certificates.

PCAPdroid 1.6.5
PCAPdroid mitm 0.15

As a added inconsistency, last i used the app was square in June 14.

**Comment by emanuele-f** [comment]
Please check out https://github.com/emanuele-f/PCAPdroid/issues/330#issuecomment-1599378312 . I will add a message in the ui for clarity
