### ISSUE TITLE
Is there any way to get the  [saddr1:sport1] when working with non-root mode?

### ISSUE THREAD

**Issue by zhenggao2** [emanuele-f/PCAPdroid#332]
When the app makes a connection, saddr1:sport1 -> daddr:dport (the original), PCAPdroid creates a new connection saddr2:sport2 -> daddr:dport (the proxied) which goes over the Internet. 
---
Is there any way to get the  [saddr1:sport1] when working with non-root mode? thanks

**Comment by emanuele-f** [comment]
Hi, the source address is the IP address of the VPN interface [10.215.173.1](https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L167), the source port is not currently visible in the UI, but it's available internally via the [local_port](https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/model/ConnectionDescriptor.java#L90C22-L90C32) member. What is your use case?

**Comment by zhenggao2** [comment]
Hi,
We have a special kind of Android phone, which has three different APNs. That's, it has three IP addresses with each for different usage(i.e, different APPs).
After trying pcapdroid, I found that the src_ip_addr of all outgoing packets are 10.215.173.1.
I need to distinguish the original IP address of each packet, so that I can make sure that a specific APP is using the correct IP address to communicate with its APP server.
thanks

**Comment by emanuele-f** [comment]
You should be able to get the local IP address from the `struct sockaddr_in' here: https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/jni/core/capture_vpn.c#L637
