### ISSUE TITLE
[Question]Can pcapdroid display full links

### ISSUE THREAD

**Issue by kryptobolt200528** [emanuele-f/PCAPdroid#333]
I am a newbie into pen testing,am still learning basics.I wanted to ask if pcapdroid can display full links like charlesproxy or burp suite when tls decryption is enabled??

**Comment by emanuele-f** [comment]
Sure,, when decryption is enabled you will be able to see full URLs, check out https://emanuele-f.github.io/PCAPdroid/tls_decryption for info about decryption.

**Comment by kryptobolt200528** [comment]
thanks,i kinda didn't want to ask this,but there's a specific app that i was trying to analyze by the name of "onstream",a third party web scraper,however it just plain rejects to work even when i flashed the xposed(lsposed)certificate unpinning module(i did that properly),any ideas what it might be doing??

**Comment by kryptobolt200528** [comment]
> It may use a custom pinning logic, you can try https://gist.github.com/akabe1/5632cbc1cd49f0237cbd0a93bc8e4452

Thanks alot.
