### ISSUE TITLE
TLS Decryption does not work on GrapheneOS

### ISSUE THREAD

**Issue by cyruscook** [emanuele-f/PCAPdroid#335]
Hello,

I am attempting to use the TLS description feature on GrapheneOS, however it seems not to work - I can do everything successfully up to the "Give PCAPdroid the permission to control the mitm addon", at which stage the "CONFIGURE" button does nothing when pressed.

Nothing is added to the logs.
I am guessing that an exception is being thrown here https://github.com/emanuele-f/PCAPdroid/blob/efa982c2c65c4fef60adcf47fa315c3b014e8608/app/src/main/java/com/emanuelef/remote_capture/fragments/mitmwizard/GrantPermission.java#L64C17-L64C17 which is not being caught.

I've looked in the "All permissions" menu for PCAPdroid and it does not list the `com.pcapdroid.permission.MITM` permission or anything similar - but perhaps this is the case for normal Android as well?
It does say "No permissions denied".

I don't think this is an issue with PCAPdroid, more likely with GrapheneOS but I thought it would be worth tracking the issue here for awareness, and also raising the need for better error handling in this particular case.

I have raised this on the GrapheneOS issue tracker: https://github.com/GrapheneOS/os-issue-tracker/issues/2318

**Comment by cyruscook** [comment]
Thanks to Daniel Micay's help, the problem seems to be that PCAPdroid mitm needs to be installed **before** PCAPdroid in order for the permissions to be understood.

Perhaps it would be a good idea to tell the user to uninstall and reinstall PCAPdroid after installing PCAPdroid mitm?

**Comment by emanuele-f** [comment]
This behavior is new to me, I never experienced this. I will do some tests to verify if this can be reproduced on standard Android roms

**Comment by takipsizad** [comment]
I had the same issue i am going to try installing mitm app before pcapdroid

**Comment by emanuele-f** [comment]
Hi @takipsizad did that solve the issue for you?

**Comment by emanuele-f** [comment]
Since this permission does not provide much security benefits and rises questions among the users, who think that it's a permission from Android, this permission will be removed in PCAPdroid 1.7.0. This fixes this issue
