### ISSUE TITLE
Uninstall and install application

### ISSUE THREAD

**Issue by smexyy** [emanuele-f/PCAPdroid#338]
By default I blocked newly installed app. I can see its blocked when open the new app but when try to uninstall and install it again, it allow the app to access the internet.

I have to remove the app package manually from firewall section to allow PCApdroid block it again.

**Comment by emanuele-f** [comment]
Hi, what are your Android and PCAPdroid versions?

**Comment by smexyy** [comment]
> Hi, what are your Android and PCAPdroid versions?

Android 13 . version 1.6.5

**Comment by emanuele-f** [comment]
Thanks for reporting, the bug is now fixed. The fix can be tested in the [latest beta apk](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.5-68daa31.apk) and it will be available in the next official release

**Comment by smexyy** [comment]
> Thanks for reporting, the bug is now fixed. The fix can be tested in the [latest beta apk](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.5-68daa31.apk) and it will be available in the next official release
Thank you.

**Comment by smexyy** [comment]
> Thanks for reporting, the bug is now fixed. The fix can be tested in the [latest beta apk](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.5-68daa31.apk) and it will be available in the next official release

Thank you.
