### ISSUE TITLE
Can't see request and response tab and non-decrypted payload

### ISSUE THREAD

**Issue by BlueClouDragon** [emanuele-f/PCAPdroid#341]
I can only see an overview and payload tabs without the request and response tabs.
How can i see request and response headers

**Comment by emanuele-f** [comment]
You need to decrypt the data, check out https://emanuele-f.github.io/PCAPdroid/tls_decryption

**Comment by emanuele-f** [comment]
Please post a screenshot of the issue and the "Build info", which you can find in the About page, under the info icon

**Comment by BlueClouDragon** [comment]
thanks for your response. and I am getting this "pcapd deamon did not spawn" error if enable root capture.
I found there is no libpcapd.so file on my device.
so I copied the file and gave rw permission to run the pcapd deamon, but still same issue.
follow is my screenshots

![Screenshot 2023-08-12 091238](https://github.com/emanuele-f/PCAPdroid/assets/37393004/b31bc675-22e2-4e3c-8285-493f7027c99a)
![Screenshot 2023-08-12 091340](https://github.com/emanuele-f/PCAPdroid/assets/37393004/adaf2326-a93c-4858-a3b0-52e19af0bfe3)
![Screenshot 2023-08-12 091358](https://github.com/emanuele-f/PCAPdroid/assets/37393004/44a6abd0-88d6-4ed1-bfaf-f32716774c47)
![Screenshot 2023-08-12 091429](https://github.com/emanuele-f/PCAPdroid/assets/37393004/f34587bc-5f82-4795-9083-ef551da3799b)

**Comment by emanuele-f** [comment]
In the first connection you have DNS, which is not encrypted, so it's ok.
In the second HTTPS connection, you can see that the status is "Encrypted" and there is no decryption error, which means PCAPdroid is not even trying to decrypt chrome. To decrypt it, you need to define a "decryption rule", either from the left drawer or by long tapping a connection and selecting "Decrypt...". You can decrypt chrome without the root capture.
Regarding the root capture issue, it works without any manual intervention. The libpcapd.so is located inside the apk and unpacked by Android, so you don't need to copy it manually. The PCAPdroid log (left drawer) may give more details about the issue. Please note that the root capture only works reliably with Magisk, so if your device is rooted with other methods it may not work. You can root the Android emulator as a workaround.

**Comment by BlueClouDragon** [comment]
so can i see request and response headers without root capture?

**Comment by emanuele-f** [comment]
Yes, but with some limitations. This is explained in the user guide. One easy to decrypt app without root is chrome

**Comment by BlueClouDragon** [comment]
thanks to your response, I tried to capture without root capture and got the HTTP tab that shows request and response headers.
but most of the requests say failed decrypt and looks like the app server declined PCAPdroid certificate.
If I run with root-capture, can pass this decline certificate issue? or it will be declined too?

**Comment by emanuele-f** [comment]
You will need to experiment with different tools, as apps implement different security measures. With root you have much more options. The user guide gives good indications

**Comment by emanuele-f** [comment]
Closing as the question has been replied. If you have more questions, please ask on the PCAPdroid group on telegram/matrix
