### ISSUE TITLE
Request: name resolution in socks5

### ISSUE THREAD

**Issue by bio12** [emanuele-f/PCAPdroid#343]
Hello,
thank you for the woderful App. Is it possible to add name resolution for the socks5 entry? Currently I have to enter the socks5 IP, but this is dynamic. I used a dynamic dns service, but the App does not accept a name, it needs the IP.

Kind Regards,

**Comment by emanuele-f** [comment]
Hi, host names are now supported. This will be available in the next PCAPdroid release. You can test it with the following beta apk: https://github.com/emanuele-f/PCAPdroid/commit/6d7708ee

**Comment by bio12** [comment]
thank you very much for the commit and the time it took. I appreciate it a lot.
