### ISSUE TITLE
Material UI 3

### ISSUE THREAD

**Issue by Sadwhy** [emanuele-f/PCAPdroid#349]
I'm surprised that nobody has said this up until now. The app would look good with a redesign. Not a priority tho.

**Comment by emanuele-f** [comment]
True, but to do a good job there is the need to rethink the user flow, as currently it's necessary to navigate to different menus. Regarding moving to a new Material version, we should check min api requirements. It's good to keep compatibility with older apis.
Is this something you would be interested in?

**Comment by Sadwhy** [comment]
Brother. I have no knowledge of coding. You do what you think should be right.

**Comment by emanuele-f** [comment]
No plan to work on the UI for now, closing this

**Comment by beedell-roke** [comment]
> https://github.com/emanuele-f/PCAPdroid/issues/349#issuecomment-1712483610

@emanuele-f, this is more important now. However, if you maintain your stance, I suggest that you re-close as unplanned.

**Comment by Sadwhy3** [comment]
This is off topic but I find it funny that it took so long for it to come around back to this, that I now actually know how to code and implement this. But I don't think I have the time to do it.
