### ISSUE TITLE
Request for Citation Details

### ISSUE THREAD

**Issue by maof97** [emanuele-f/PCAPdroid#350]
Hello,

First of all, I would like to express my gratitude to you and all the contributors to this project. The app and especially the possibility to export connections as a CSV has significantly aided me in my research efforts for my bachelor thesis.

As I am in the process of drafting my thesis, I find it essential to properly acknowledge the hard work and effort put into this project. Therefore, I am reaching out to inquire how you would prefer this project to be cited in academic works.

Would you prefer a standard citation to the GitHub repository, or is there a related research paper or publication that you would prefer I cite? Also, please let me know the preferred citation format (APA, MLA, Chicago, etc.) and any specific details that you would like included in the citation.

Thank you once again for your invaluable contribution to the community through this project. I look forward to hearing from you soon to ensure proper attribution in my research.

**Comment by maof97** [comment]
@emanuele-f  Hello, the thesis is done and graded and I am allowed to share it now. Thanks again for the app! It has made the whole research much easier!
[GrapheneOS_Thesis.pdf](https://github.com/emanuele-f/PCAPdroid/files/13301247/GrapheneOS_Thesis.pdf)

**Comment by emanuele-f** [comment]
@maof97 loving the PCAPdroid intro in section 2.3 😁 Thanks for sharing, I wish you the best!
