### ISSUE TITLE
Connections Export only 119 Bytes (header only)

### ISSUE THREAD

**Issue by TobiasReich** [emanuele-f/PCAPdroid#352]
When exporting my connections I usually get a nicely formatted csv file.
However when I gave the app another try this time I get only a 119 bytes small file showing only the csv header.

> IPProto,SrcIP,SrcPort,DstIp,DstPort,UID,App,Proto,Status,Info,BytesSent,BytesRcvd,PktsSent,PktsRcvd,FirstSeen,LastSeen

Any idea what I'm doing wrong? There are no permissions missing or anything. Is there a setting I might have missed?
(The connections are logged and visible so I know there is something, the PCAP file is several MB large so that worked, just not the connections export)

**Comment by emanuele-f** [comment]
PCAPdroid version? Do you remember the version number that worked correctly?

**Comment by emanuele-f** [comment]
@TobiasReich any updates? I cannot reproduce this with latest PCAPdroid (1.6.8)
