### ISSUE TITLE
Live capture button And always on vpn

### ISSUE THREAD

**Issue by smexyy** [emanuele-f/PCAPdroid#356]
Hello, I'm not sure if this the default or not.

Issue: -

When pcap live capture is disabled and toggle on always on vpn the button enable pacp to capture is disabled. I have to enable first live capture then toggle on always on vpn.

![Screenshot_20231016-064137~2](https://github.com/emanuele-f/PCAPdroid/assets/135754251/8bfbe80b-b05f-450c-b7ea-4bdb08239337)

**Comment by emanuele-f** [comment]
When the always-on vpn is active, the start/stop button is hidden because the capture should be always on

**Comment by smexyy** [comment]
> When the always-on vpn is active, the start/stop button is hidden because the capture should be always on

Thank you
