### ISSUE TITLE
SSDP (UDP) discovery

### ISSUE THREAD

**Issue by neon12345** [emanuele-f/PCAPdroid#359]
I have an app that tries to discover other devices using SSDP. Should this work with the VPN proxy? Unfortunately it does not for me.

Thanks

**Comment by emanuele-f** [comment]
I experienced the same issue in the past, in essence the vpn subnet will be used for SSDP discovery instead of the wifi interface. I don't know any workaround for this, apart from from using the root capture

**Comment by neon12345** [comment]
There seem to be ways around this, but I can't say if this is applicable here: [VLC](https://github.com/vvd170501/VLC-Android-vpn-dlna)

**Comment by emanuele-f** [comment]
> There seem to be ways around this, but I can't say if this is applicable here: [VLC](https://github.com/vvd170501/VLC-Android-vpn-dlna)

Interesting link. [This patch](https://github.com/vvd170501/VLC-Android-vpn-dlna/blob/master/patches/0002-Add-auto-detection-for-multicast-interface.patch) for automatic detection of multicast could work, provided that PCAPdroid does not route 239.255.255.250 via the VPN (currently [it does](https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L430)).

Assuming that the app you are using uses a similar detection as of the patched VLC version, please try this patched apk and see if it solves the problem [PCAPdroid-debug-ssdp-fix-500db74.apk.zip](https://github.com/emanuele-f/PCAPdroid/files/13339728/PCAPdroid-debug-ssdp-fix-500db74.apk.zip) (you need to unzip first)

**Comment by neon12345** [comment]
You mean I need a patched version of my app? Would it be possible to resend the UDP broadcast on the wifi interface from PCAPdroid, wait for a response and reply from PCAPdroid through the vpn to the app? The reply through vpn is a problem 
 I guess?

**Comment by emanuele-f** [comment]
I mean, you can try the patched PCAPdroid apk above to see of it works. If not, probably it's something to fix on your app.

Regarding the possibility for PCAPdroid to proxify multicast datagrams, it looks complex

**Comment by emanuele-f** [comment]
@neon12345 any update? Did the apk I sent above work?

**Comment by emanuele-f** [comment]
@neon12345 thanks for getting back.
For now I will close the issue, as there are no other practicable fixes that come to my mind. If you have any new insights please let me know.
