### ISSUE TITLE
Gzip encoded json text 

### ISSUE THREAD

**Issue by pabx06** [emanuele-f/PCAPdroid#360]
Ability to view captured data in human readble format

HTTP header:
Content-type: application/json
Content-encoding: gzip
![Screenshot_20231029_124953_PCAPdroid](https://github.com/emanuele-f/PCAPdroid/assets/4013370/ed233051-a51a-4847-8a6d-9d2a33bb9093)

**Comment by emanuele-f** [comment]
This is weird, PCAPdroid already deconpresses gzip.
Can you provide a pcap file to reproduce this? You can send it via email if you prefer

**Comment by emanuele-f** [comment]
@pabx06 any update?
