### ISSUE TITLE
Easily save http(s) response body

### ISSUE THREAD

**Issue by narumi147** [emanuele-f/PCAPdroid#362]
I may be blind, but didn't find an easy way to save the http or decrypted https response body. 
I have to choose all and share it to another text editor to save the response. However, if the response body is too large, the "choose all" action will only select one paragraph.
As for save PACP to device and look up data in other application (not tested and not familar with PACP format and tools), it's a bit annoying, since the response data is already there and I can see the data, why there is no action to save it?

Suggestion: besides the "expand" icon, add a save button, prompt a dialog to choose what to save: text/binary/full data with headers.

Sorry if I miss the feature already exist.

Example:
<img width="422" alt="image" src="https://github.com/emanuele-f/PCAPdroid/assets/56487872/12605c25-39aa-482b-b6e5-7a0d661e7b73">

- [x] Add copy payload button
- [x] Add ability to copy hexdump/plaintext for non HTTP connections and hexdump or only the HTTP header/body/both for HTTP connections
- [x] Add save to file button with the same options of the copy button

**Comment by emanuele-f** [comment]
Thanks for your suggestion. Sometimes it's not immediately clear how a simple feature can speed up a user interaction flow

**Comment by emanuele-f** [comment]
@narumi147 hopefully I will have some free time in these holidays, I would say 1-2 months but cannot be sure. In any case, I can provide a beta APK if you want to test and share this before the official release

**Comment by emanuele-f** [comment]
A new copy button has been added to the request/response header. You can test this feature with the [latest PCAPdroid beta apk](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.9-d5661be.apk).

![2023-12-25_11-44](https://github.com/emanuele-f/PCAPdroid/assets/5488003/818f3736-fa7d-4c97-b86f-2b16410fba74)

**Comment by emanuele-f** [comment]
In this case I had decryption disabled. When the payload is decrypted, the copy function will copy the decrypted one. Also gzip is automatically decoded and copied. The payload is either copied as printable text or as hexdump, depending on the current visualization

**Comment by emanuele-f** [comment]
@narumi147 do you have any other feedback on the new feature? Can we close this?

**Comment by emanuele-f** [comment]
Hello, thanks for your feedback. Please see below.

> raw binary for any connection
> header only/body only/both for http(s)

I will add the ability to copy hexdump/plaintext for non HTTP connections and hexdump or only the HTTP header/body/both for HTTP connections

> Add a 'save to file' button

A save to file button seems handy, I will add it with the same options of the copy button

> hex+ascii is messed up(for each line, left is hex and right is ascii) because we don't know the binary format, for copy, ascii after hex is better?

This hexdump format is often called hex+ASCII, it allows you to visualize both printable (on the right) and non-printable (on the left) characters

> Even full payload is off, this save button should always be able to save correctly?

For the time being we can just keep the copy/save buttons even if full payload is disabled. For future improvements of this feature, I've open #398

**Comment by emanuele-f** [comment]
@narumi147 thanks for your in-depth testing and suggestions!

Please find [here](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.9-2bb955a.apk) a new beta for testing, with the following improvements.

> when body is empty, click copy or save button will both directly show copied, at least save button should show save rather copy

bug fixed

> headers/body/both: body is better than both as default selection

done

> for save, always save(gzip/br/deflate decoded) body bytes rather the shown text, because some are not text format, like image.

fixed, now when exporting the HTTP body, the raw bytes will be exported

> when picking save location, respect the input filename extension

fixed, now the correct extension will be used. Also, when exporting the HTTP body, the actual file name will be used

> text decode and multi-response

in the HTTP tab, PCAPdroid performs reassembly and decoding of the HTTP body, so the response should be shown in a single chunk. The payload tab, on the other hand, it's meant to show the raw payload, without any decoding, so there you may see multiple chunks for a single response, e.g. as in the following image. This is expected

![2024-02-05_12-15](https://github.com/emanuele-f/PCAPdroid/assets/5488003/f06b386a-e6e9-4396-989e-2c0341f25819)

> still for save, in payload tab, there are 2 options printable text and hex dump, I hope raw bytes could be added too.

in the payload tab, there is now a "Raw bytes" option, but only for "export", not for "copy", as it's not possible to copy raw bytes to the Android clipboard

> In emulator (LD5 Android7), click copy show copied but clipboard is empty

this depends on your emulator configuration, it does not depend on PCAPdroid. On linux, using the Android emulator provided by Android studio, copying something in the emulator will also copy it to the host clipboard

**Comment by emanuele-f** [comment]
Please find the fixes [here](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.9-69f06c2.apk).

> after some consideration, I think it's better to show dialog to let user know body is empty, and you can only copy/save headers. If body is empty, hide or disable body/both options.

For now I prefer the current behavior, without a prompt in this case. Moreover, I will improve the dialog in the future to close it as soon as a radio option is selected, without the need to click save/export. I prefer to remove unnecessary steps

> use final segment of "path" only, remove query

my bad, fixed

> add case "application/json": ext = "json";, which is useful for many api

done

> not fixed issue: If default filename is used, like PCADroid_01_01_01.txt, when I change it to .css extension, app will still add .txt

Android will normally force the file extension, I've pushed a workaround for this. Hopefully this will work consistently across different Android versions and roms. If not, I will probably revert it

> body here is using plaintext or bytes

in this case, both the body and header will be saved as text. The body will be encoded as "printable text". The only case where the body is saved in binary form is when only the body is exported or in the case of "raw bytes" from the payload tab
