### ISSUE TITLE
Is it possible to save captured datas as protobuf?

### ISSUE THREAD

**Issue by aktayozan** [emanuele-f/PCAPdroid#363]
I'm capturing an application's traffic with pcapdroid. It's sending requests as tcp with protobuf datas. The problem is i can not decode these datas because i can not save these datas as protobuf datas. 

![Ekran görüntüsü 2023-11-14 220335](https://github.com/emanuele-f/PCAPdroid/assets/93337751/8e6091e2-5278-4429-85c7-63a5b58271d2)

Opened the pcap file and ssl key log file with wireshark but still can not decode as protobuf data. Is it possible to save these raw protobuf datas as byte array or strings or proto file?

The question is: The payload can be decode as protobuf?

![Ekran görüntüsü 2023-11-14 222241](https://github.com/emanuele-f/PCAPdroid/assets/93337751/b5ef2cf6-5149-4a9d-80fe-d108f8eb8c45)

**Comment by emanuele-f** [comment]
You can find online some tools to decode protobuf even without the original .proto files

**Comment by emanuele-f** [comment]
Closing for now
