### ISSUE TITLE
Is there a way not to allocate IPv6?

### ISSUE THREAD

**Issue by innotestdm** [emanuele-f/PCAPdroid#366]
I shouldn't use IPv6 in the environment that I want to test, but when I start capturing, I'm assigned an IPv6 address, so I can't test it. Is there a way?

**Comment by innotestdm** [comment]
Is there any way to prevent IP allocation up to IPv6 even if I set up Capture with IPv4 Only?

**Comment by emanuele-f** [comment]
In the PCAPdroid settings, specify "IPv4 Only" in the VPN ip addresses option.
If you want to prevent the device from getting an IPv6 address, in the Android network setting assign a static ipv4

**Comment by emanuele-f** [comment]
It's in the wifi advanced options, see https://www.youtube.com/watch?v=24OQ39OhEms

**Comment by emanuele-f** [comment]
Hi @jinguwatford,
Indeed that is the IPv6 address used by PCAPdroid, but that is only used *if you enable IPv6 in PCAPdroid* (see [the check here](https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L437C30-L437C30)). If you set "IPv4 only", then it won't be used, I've double checked this.

![2023-12-02_15-09](https://github.com/emanuele-f/PCAPdroid/assets/5488003/aa65eefa-5064-4391-b52d-1f594e4ef025)

**Comment by emanuele-f** [comment]
> If you intended to advise the latter, I would like to propose you try the process I took above.

This is what I meant. The IPv6 address is not created at all if the ipv4-only option is specified. I also checked with ifconfig.

Are you starting the capture manually from the PCAPdroid Ui or maybe using the intent-based api to start PCAPdroid from another app?

**Comment by jinguwatford** [comment]
Dear Emanuele,

I am using App itself and not using any api. I prepared three screem captures which should explain what I experience and expect. I also attach the ifconfig outcomes for each case.

![1](https://github.com/emanuele-f/PCAPdroid/assets/152635860/52069d8c-a9dd-4b70-a3d8-58ae34c71b84)
![2](https://github.com/emanuele-f/PCAPdroid/assets/152635860/93e95b16-003b-469b-8091-52ab38a740f2)
![3](https://github.com/emanuele-f/PCAPdroid/assets/152635860/09f6775d-6645-4bfb-a6f1-8c5ef9b42068)

[ifconfig - IPv4 and IPv6 Configured at Settings.txt](https://github.com/emanuele-f/PCAPdroid/files/13550391/ifconfig.-.IPv4.and.IPv6.Configured.at.Settings.txt)
[ifconfig - IPv4 Only Configured at Settings.txt](https://github.com/emanuele-f/PCAPdroid/files/13550392/ifconfig.-.IPv4.Only.Configured.at.Settings.txt)
[ifconfig - IPv6 Only Configured at Settings.txt](https://github.com/emanuele-f/PCAPdroid/files/13550393/ifconfig.-.IPv6.Only.Configured.at.Settings.txt)
[ifconfig - no capturing.txt](https://github.com/emanuele-f/PCAPdroid/files/13550394/ifconfig.-.no.capturing.txt)

**Comment by emanuele-f** [comment]
Hello, the fe80 ipv6 is a link local address, and it's assigned by Android itself, it's not something I can control from the app.
I don't think there is a way to disable it in Android, but it's strange to me that it creates issues on your project. Can you explain in more detail the issue that you are experiencing with it?

**Comment by emanuele-f** [comment]
Hi @jinguwatford , do you have any update?

**Comment by emanuele-f** [comment]
No reply received, will reopen if anything changes
