### ISSUE TITLE
1.6.9 Incompatibly with latest mitm plugin (0.16)

### ISSUE THREAD

**Issue by lbrunkho** [emanuele-f/PCAPdroid#371]
I have the latest github release of PCAPdroid installed (v1.6.9) and the latest release of PCAPdroid mitm addon (v0.16) installed. 

When I go to enable the TLS decryption function, I am presented with the following message...

![Screenshot_20231204-194334](https://github.com/emanuele-f/PCAPdroid/assets/24943712/ec5c0963-98e4-4aa3-b7d6-644443e61055)

I am using these apps on GrapheneOS inside a work profile. 

I would roll the mitm plugin back to v0.15, but the changelog for v0.16 explicitly states fixes for GrapheneOS users. 

Thanks!

**Comment by emanuele-f** [comment]
Hello, they are not compatible. The latest mitm addon release is just a preview for PCAPdroid 1.7.0.
If you can already start the TLS decryption, no worries, you don't need the fix from the latest addon version.
