### ISSUE TITLE
Custom rules per app

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#374]
Thank you so much for your program :)
Are you planning to add host/ip whitelist and blocklist per application? 
As I understand it, there is only a single global whitelist and blocklist now.

**Comment by emanuele-f** [comment]
Hello, thanks for your feedback. Can you provide more insights on your use case for this feature?

**Comment by anpic** [comment]
> Can you provide more insights on your use case for this feature?

It's often necessary to manage addresses individually in each app.
How is this done in Rethink
https://github.com/celzero/rethink-app
There are both general lists for all apps and separate ones for each app.

**Comment by emanuele-f** [comment]
Thanks for the pointers. As this will add more complexity to the app, unless we have a specific use case which is worth, this is a feature I would reject

**Comment by anpic** [comment]
> unless we have a specific use case which is worth

Well, does the application need to be allowed to go to some addresses and not be allowed to go to others?  Specifically for a separate application.
How do I do this without affecting other applications?

**Comment by anpic** [comment]
This is a common feature in all configurable firewalls.

**Comment by emanuele-f** [comment]
> This includes blocking ads and trackers in individual applications.

See https://github.com/emanuele-f/PCAPdroid/issues/375#issuecomment-1854350170 :D

> How do I do this without affecting other applications?

Yeah I understand. But as explained in the linked comment, this use case is quite problematic for the survival of the app. I will keep your suggestion in consideration, but at the current stage I would not go this path

**Comment by anpic** [comment]
> but at the current stage I would not go this path

It's up to you :)
But other firewalls have been around for many years.
After all, you've already added functionality in the form of a separate plugin.

**Comment by emanuele-f** [comment]
Not planned for now
