### ISSUE TITLE
Default whitelist apps

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#376]
Several system apps and PCAPdroid itself are added to the firewall whitelist by default.
How important is this and why wasn't the list made initially empty?

**Comment by emanuele-f** [comment]
It's necessary to prevent the firewall from blocking core phone services, like push notifications

**Comment by anpic** [comment]
> It's necessary to prevent the firewall from blocking core phone services, like push notifications

That's if need to block everything at all then can safely delete them from there?
And why is the PCAPdroid itself added there?

**Comment by emanuele-f** [comment]
Yes, you can delete them. As I said, they are there by default to ensure that a user blocks essential services by error

**Comment by anpic** [comment]
> As I said, they are there by default to ensure that a user doesn't block essential services by error

It seems to me that this is also not a very good solution.
I turn on the whitelist mode and wait for the complete absence of external traffic but there is one. And have to think about why it exists.
It may be worth making a separate menu item or setting. In general, I would like to manage everything through intents ;)

**Comment by emanuele-f** [comment]
Well, the dumb user will enable whitelist mode and see that the phone does not work anymore. Then he will complain that pcapdroid broke it. My first priority is to prevent this 😂

Regarding a possible intent-based api, it can be cool to configure pcapdroid via intents, but security is also a point. This should be evaluated with some practical use case. This is something very specific, that can benefit only very few users

**Comment by anpic** [comment]
> but security is also a point

Do it like Google!
Want to turn on a super dangerous thing? Press a few buttons and check a few checkboxes :)
As an example, USB Debugging and ADB.
But if you need more than just dumb users (you probably didn't make MITM plugin for them, did you?) then need management flexibility.
Either through intents or through exported configs. Although one does not interfere with the other ;)

**Comment by anpic** [comment]
> My first priority is to prevent this

You can make options for everyone.
But then you will have to do them or enjoy what you already have ;)
