### ISSUE TITLE
How do i export the CA certificate?

### ISSUE THREAD

**Issue by NastyFlytrap** [emanuele-f/PCAPdroid#378]
Android 13 on Samsung A32 4G

Admittedly i have used ADB to remove a bunch of system apps so maybe one of them had the ability to export certificates and thats why i cant do it now, but i dont know... It says no app found to handle file selection

 I press the export button and nothing happens. Tried looking for autostart in the settings but found nothing

**Comment by emanuele-f** [comment]
The easiest path is to reinstall an app which handles file selection. Alternatively, if you have root, you can find the cert in the mitm app private data directory

**Comment by NastyFlytrap** [comment]
> The easiest path is to reinstall an app which handles file selection. Alternatively, if you have root, you can find the cert in the mitm app private data directory

Well damn. Every file selection app seems to be missing deep features like this. Neither material files nor amaze does this and i've had this happen before. 

Alright, thanks.

**Comment by barium56** [comment]
Had the same problem, android device (ebook reader) without a file picker. The instructions by @spvkgn didn't work for some.
Solved this by using [Apktool M](https://maximoff.su/apktool/?lang=en).
`Applications` → `Installed Applications` → `PCAPdroid-mitm` → `Quick edit` → Tick `set apk as debugable` → Press on `SAVE` → Uninstall PCAPdroid-mitm → Install the new APK → Generate Cert with PCAPdroid

Then on your PC:
`adb shell`
`run-as com.pcapdroid.mitm cat /data/user/0/com.pcapdroid.mitm/files/.mitmproxy/mitmproxy-ca-cert.cer > /storage/emulated/0/mitmproxy-ca-cert.cer`
