### ISSUE TITLE
Whitelist actions

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#381]
Why are there Host and IP items available for adding to Blocklist but there no similar items for Whitelist? ;)

**Comment by emanuele-f** [comment]
Mainly ease of implementation, due to the limited use case

**Comment by anpic** [comment]
> Mainly ease of implementation, due to the limited use case

This is in the same piggy bank as https://github.com/emanuele-f/PCAPdroid/issues/374  :)
I really miss it.
I have to communicate with other so-called developers who don't understand how to make the firewall itself ;)

**Comment by anpic** [comment]
And so I missed the same one issue https://github.com/emanuele-f/PCAPdroid/issues/302

**Comment by emanuele-f** [comment]
Right, this is a duplicate of #302
