### ISSUE TITLE
Adding to Blocklist and Whitelist by UID

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#382]
As I understand it, you can identify all available UIDs even in a non-root mode.
According to this
https://android.googlesource.com/platform/system/core/+/master/libcutils/include/private/android_filesystem_config.h
It would be fair to let users manage them too ;)
Especially if you add some global rules that users cannot influence.

**Comment by emanuele-f** [comment]
There are only some corner cases (e.g. termux) where you don't have a 1:1 match between UID and package name. For all practical use-cases, blocking via package name is basically the same. What is the use of this?

**Comment by anpic** [comment]
> For all practical use-cases, blocking via package name is basically the same. What is the use of this?

I didn't expect this from you :)
Then remove it from source code
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/AppsResolver.java
`mApps.put(Utils.UID_UNKNOWN, new AppDescriptor(mContext.getString(R.string.unknown_app),
             unknownIconLoader, "unknown", Utils.UID_UNKNOWN, true)
            .setDescription(mContext.getString(R.string.unknown_app_info)));
        mApps.put(0, new AppDescriptor("Root",
                virtualIconLoader,"root", 0, true)
                .setDescription(mContext.getString(R.string.root_app_info)));
        mApps.put(1000, new AppDescriptor("Android",
                virtualIconLoader,"android", 1000, true)
                .setDescription(mContext.getString(R.string.android_app_info)));
        mApps.put(1001, new AppDescriptor(mContext.getString(R.string.phone_app),
                virtualIconLoader,"phone", 1001, true)
                .setDescription(mContext.getString(R.string.phone_app_info)));
        mApps.put(1013, new AppDescriptor("MediaServer",
                virtualIconLoader,"mediaserver", 1013, true));
        mApps.put(1020, new AppDescriptor("MulticastDNSResponder",
                virtualIconLoader,"multicastdnsresponder", 1020, true));
        mApps.put(1021, new AppDescriptor("GPS",
                virtualIconLoader,"gps", 1021, true));
        mApps.put(1051, new AppDescriptor("netd",
                virtualIconLoader,"netd", 1051, true)
                 .setDescription(mContext.getString(R.string.netd_app_info)));
        mApps.put(9999, new AppDescriptor("Nobody",
                virtualIconLoader,"nobody", 9999, true));`
;)

**Comment by anpic** [comment]
If you started adding filtering by uids then you need to make its control available to all users.
Are you making a universal firewall that can be reconfigured as we like or in which there will be a lot of global rules beyond the control of users? ;)

**Comment by anpic** [comment]
It seems like you want to make a root version of PCAPdroid yourself.
This will be the main step towards such a version.
But even outside of the root version, this is an opportunity for users to fully configure the firewall.

**Comment by anpic** [comment]
This is primarily about other lists: about app block and white lists.

**Comment by anpic** [comment]
Moreover, you have already partially done it ;)
After all can add and remove app from Connections log.
But it's very inconvenient if need to create app lists beforehand.

**Comment by anpic** [comment]
It seems to me that this is a problem from the same category: you can't decide in any way whether to make the best firewall for android or not ;)

**Comment by emanuele-f** [comment]
You are asking for something which is already implemented in PCAPdroid, the ability to block apps. Adding the ability for users to specify a UID is only a complication, the result is the same. The current behavior will be kept

**Comment by anpic** [comment]
> Adding the ability for users to specify a UID is only a complication, the result is the same.

But in another similar project, they spy on yours and pick up the issues themselves
https://github.com/celzero/rethink-app/issues/1167
But it's clear that you don't have their resources, human and financial :(
