### ISSUE TITLE
Tun2Socks implementation

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#383]
Have you looked towards implementing a firewall through Tun2Socks?
As I understand it, you can create a separate mode specifically for the firewall only.
Without packet modification. Without showing the payload.
When we need a guaranteed absence of any third-party effects that may occur when recreating packets. But only filtering and redirecting connections.
In addition then it was possible to use PCAPdroid in socks proxy chains.

**Comment by anpic** [comment]
> Have you looked towards implementing a firewall through Tun2Socks? As I understand it, you can create a separate mode specifically for the firewall only. Without packet modification. Without showing the payload. When we need a guaranteed absence of any third-party effects that may occur when recreating packets. But only filtering and redirecting connections.

**Comment by emanuele-f** [comment]
In Android, without root, the only way to filter packets like a firewall does is to use the VPNService, which requires an app to modify the packets. Without doing this, you are only limited to DNS-level filtering, which is quite limiting. If you want to discuss more on the topic, please head to https://github.com/emanuele-f/PCAPdroid/discussions

**Comment by anpic** [comment]
> does is to use the VPNService

It's about exactly how to filter packets inside VpnService. You can interfere and recreate packets in traffic or you can simply redirect.
Now you're interfering with traffic, which is not necessary in firewall mode.

> If you want to discuss more on the topic

I don't need to discuss, I am interested in the possibility of implementation. Who is there and what is there to discuss, if you will not participate in the discussion anyway.
If you aren't going to change or add anything to the project at all, tell everyone so directly ;)
Your contribution is already huge, you can afford to speak frankly :)
But you don't need to close issues so that you can just close them quickly and pretend that there is nothing useful in them.

**Comment by emanuele-f** [comment]
> You can interfere and recreate packets in traffic or you can simply redirect

If it was possible to simply redirect, that would have saved me and a similar projects a lot of work. Unfortunately, this is not possible. You are making wrong assumptions on how things work. You should not talk just based on your assumptions, that will only waste people time

**Comment by anpic** [comment]
> You should not talk just based on your assumptions, that will only waste people time

Well, let's figure it out?
tun2socks is a free cross-platform project for combining a virtual network adapter and a socks server
https://github.com/xjasonlyu/tun2socks/wiki
And allows to easily create proxy chains
https://github.com/xjasonlyu/tun2socks/wiki/Proxy-Models
A Go version was created based on it:
https://github.com/eycorsican/go-tun2socks
And then an userspace version for android was created based on go version:
https://github.com/Jigsaw-Code/outline-go-tun2socks
In Rething uses its own fork:
https://github.com/celzero/firestack
There is also a cool implementation:
https://github.com/heiher/hev-socks5-tunnel
https://github.com/heiher/sockstun
So it's about redirecting packets without modifying them:

> Redirect TCP connections.
> Redirect UDP packets. (Fullcone NAT, UDP in UDP/TCP)
> Simple username/password authentication.
> Specifying DNS addresses.
> IPv4/IPv6 dual stack.
> Global/per-App modes.

Can see it:
https://github.com/heiher/sockstun/blob/master/app/src/main/java/hev/sockstun/TProxyService.java#L64
A VpnService is created, the specified parameters are assigned to it, and then the native method TProxyStartService is called from
https://github.com/heiher/hev-socks5-tunnel/blob/master/src/hev-jni.c#L50
https://github.com/heiher/hev-socks5-tunnel/blob/master/src/hev-jni.c#L97
And the descriptor of the created VpnService is passed to him, from which traffic is redirected.
Rethink uses a more complicated variant
https://github.com/celzero/rethink-app/blob/main/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L1202
https://github.com/celzero/rethink-app/blob/main/app/src/main/java/com/celzero/bravedns/net/go/GoVpnAdapter.kt#L82
https://github.com/celzero/firestack/blob/n2/intra/android/tun2socks.go#L55
etc
In general, it seems to me that they complicate everything so carefully and hide details for a reason. But these are the problems of their users :)

Thus, if only the firewall functionality is needed, then it's not necessary to change the traffic packets, which can lead to unnecessary effects. But it's enough only to redirect it to tune2socks server.
Moreover, such a scheme makes it easy to participate in the creation of proxy chains, which is a very necessary feature in conditions of the possibility of creating only one VpnService in Android.
It seems to me that it's difficult to implement this in your version because you process packets in the same service:
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L216
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/java/com/emanuelef/remote_capture/CaptureService.java#L1068
https://github.com/emanuele-f/PCAPdroid/blob/master/app/src/main/jni/core/jni_impl.c#L562
It's very cool if need to inspect packets.
But when only the firewall feature is needed and it's necessary to preserve the authenticity of the original packets, it's superfluous ;)

**Comment by emanuele-f** [comment]
Interesting, seems like you can read and understand Java, C and JNI, so you could already actively contribute to this project 😉

> And the descriptor of the created VpnService is passed to him, from which traffic is redirected.

This is the right approch, reason on the code.
You just need to go a bit deeper, to understand the underlying technology used.
In https://github.com/heiher/hev-socks5-tunnel/blob/master/src/hev-socks5-tunnel.c#L182 it reveals that lwip is used, a tcp/ip stack implementation. If a redirection is done, that is done by modifying packets as PCAPdroid does. This is a limit of the Android API

**Comment by anpic** [comment]
> Interesting, seems like you can read and understand Java, C and JNI, so you could already actively contribute to this project

Sometimes things are not what they seem ;)

> You just need

I don't need to, I'm not a developer.
I just think your project is the best among the others and I'm trying to bring some of my understanding to it.
But you didn't notice how you suddenly jumped from the fact that I was taking time away to the fact that why am I not writing code in your project? ;)

> If a redirection is done, that is done by modifying packets as PCAPdroid does

That's why you're a great developer, and I'm just a concerned admirer of your project and connoisseur of various others things :)

**Comment by anpic** [comment]
> This is a limit of the Android API

I thought so too. But Rethink developers made me doubt it. And since they intentionally hide all the details, I had to check with other specialists.
Of course, there may be some magic holes open in Rethink's Firestack or Outline, but they probably just either don't understand how things work under the hood or are trying to denigrate your approaches.
