### ISSUE TITLE
USB Wifi Monitor App

### ISSUE THREAD

**Issue by mosee101** [emanuele-f/PCAPdroid#384]
I bought a WIFI AR9271 adapter from Amazon to test this app.
Unfortunately my Samsung S22 no-root device does not recognized it.

Can you please help me, I will even supply funds to you if you can help me with this.

Thank you for making this app, nothing like it on the play store. I am confident I will get it working eventually.

**Comment by emanuele-f** [comment]
Hello, please get in touch via email at black.silver@hotmail.it , as this repo is for PCAPdroid. You need to specify: Android version, the model of the adapter that you got, and if anything happens when you connect the adapter to the phone
