### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#387]
AFWall has this feature.
When can change the white and block app lists manually or by events.
It's also a very useful feature.

![Profiles](https://github.com/emanuele-f/PCAPdroid/assets/40465616/3d6249cc-5e30-4a60-addf-55b00bb7d16e)

**Comment by emanuele-f** [comment]
Sorry but I don't have time to properly evaluate and implement this. You can head to https://github.com/emanuele-f/PCAPdroid/discussions if you plan for a long term discussion

**Comment by anpic** [comment]
> Sorry but I don't have time to properly evaluate and implement this

That's how it should have been written everywhere ;)
I hope you will come back to the project someday, evaluate everything and reopen all.
Merry Christmas :)
