### ISSUE TITLE
Summary statistics

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#388]
It would be very useful to look at summary statistics on various parameters. Such as app name, app uid, connection status, interface, protocol, source host and port, destination host and port, traffic, packets etc.
And the ability to filter by their combinations through logical operations AND OR.
Or at least just get these statistics through intents.

**Comment by emanuele-f** [comment]
This is too generic (in the purpose) and too low level (most people don't use intents or know what logical operators are). This won't be implemented

**Comment by anpic** [comment]
> This is too generic (in the purpose)

It's about systematizing information from your usual logs.
Then it was possible not to add them either ;)

> and too low level (most people don't use intents or know what logical operators are)

You don't even read it, you just grab some words and close the issues  just to close them quickly.
It's a pity that everything is so bad with your time :(
