### ISSUE TITLE
Unblock for 10 Min

### ISSUE THREAD

**Issue by smexyy** [emanuele-f/PCAPdroid#390]
Hello, when trying to ublock the app for some time for example 10 Min, it keeps allowed and not auto blocked after the the duration end.

![Screenshot_20231225-143308~4](https://github.com/emanuele-f/PCAPdroid/assets/135754251/d4b8e5bf-32bf-4eb8-afbb-f37c83ef8998)

Phone Info: - Pixel 6a - android 14
Pcap version - 1.6.9

Note: this happen in this phone not my other phone.

**Comment by emanuele-f** [comment]
Hello, is the hourglass icon still displayed after the 10 minutes pass? Does the same happen with other apps like chrome?

**Comment by smexyy** [comment]
- Yes still displayed after the 10 M ,1H ,8 H.
- Yes For any/other apps
- And the connection keep open and I have to manually block it.

**Comment by emanuele-f** [comment]
@smexyy in the screenshot above, I can see the check icon, which indicates that the firewall is working in whitelist mode (block everything except the whitelisted apps) and that whatsapp is whitelisted, so this is why the app is unblocked even if the grace period has ended.
The bug to fix here is that PCAPdroid allows you to temporary unblock an app which is already whitelisted.

**Comment by emanuele-f** [comment]
I've tested this on Android 14 and could not reproduce it. Please try with [this beta APK](https://pcapdroid.org/fdroid/repo/PCAPdroid_1.6.9-e0112ea.apk) and post here the App log, which you can find in the left drawer of PCAPdroid

![2023-12-25_18-34](https://github.com/emanuele-f/PCAPdroid/assets/5488003/be4225a9-f9ae-4873-81d5-0eacb4e1d97d)

**Comment by smexyy** [comment]
> @smexyy in the screenshot above, I can see the checkmark icon ✅, which indicates that the firewall is working in whitelist mode (block everything except the whitelisted apps) and that whatsapp is whitelisted, ~so this is why the app is unblocked even if the grace period has ended. The bug to fix here is that PCAPdroid allows you to temporary unblock an app which is already whitelisted.~
> 
> Edit: actually block rules co-exist with whitelist rules, as explained in the whitelist help dialog, so this is not the case

I add some apps in whilelist and add the same apps in blocklist, and when I need to allow connection, I allow the app for 10 Min use and it will auto block again after grace period end. this issue happen only with my pixel 6a not my other phone which is the same setup.

**Comment by emanuele-f** [comment]
I see, I will need the log to investigate further

**Comment by smexyy** [comment]
> Hello, is the hourglass icon still displayed after the 10 minutes pass? Does the same happen with other apps like chrome?

I tested now and seems not all apps, it random apps. after 10 min it takes some time to revert back to block sign again.

**Comment by emanuele-f** [comment]
>I tested now and seems not all apps, it random apps. after 10 min it takes some time to revert back to block sign again.

@smexyy please provide the app log as explained in https://github.com/emanuele-f/PCAPdroid/issues/390#issuecomment-1869064688, it's necessary to proceed with the troubleshooting

**Comment by emanuele-f** [comment]
I reproduced this. The bug occurs when the device enters deep sleep, as https://developer.android.com/reference/android/os/SystemClock#uptimeMillis() does not count time spent sleeping
