### ISSUE TITLE
Using /sdcard as a database location

### ISSUE THREAD

**Issue by anpic** [emanuele-f/PCAPdroid#393]
There is a solution to this problem https://github.com/emanuele-f/PCAPdroid/issues/379
Start using sdcard to save the geolocation database.
Saving the database in /sdcard/Android/data/com.emanuelef.remote_capture/ by default
Or to some other directory of the user's choice.
Then you really only have to export and import SharedPreferences

**Comment by emanuele-f** [comment]
It does not make sense to save the geolocation database, as it's something that can be downloaded at any time. This is rejected

**Comment by anpic** [comment]
> as it's something that can be downloaded at any time

Excellent understanding of automation tasks :)
And if it needs to be done on hundreds of devices? A thousand?
Okay, there's no time, so there's no time :(

**Comment by emanuele-f** [comment]
No it's not about time, this just does not make sense. Under any circumstances, in any universe

**Comment by anpic** [comment]
> Under any circumstances, in any universe

Well, if you are aware of this so clearly, how can you automate the complete transfer of all app settings without internet on a local network between any number of devices?
In my universe, need to downgrade the target version of PCAPdroid and make a data backup by bu or adb.
And in yours?

**Comment by emanuele-f** [comment]
Again, the geolocation database is not an app setting, there is no use to back it up. Using without Internet is yet another unfeasible use case, and if you really want, you can download yourself after doing the backup, this discussion and task has no sense

**Comment by anpic** [comment]
> Again, the geolocation database is not an app setting

What? ;)
Don't believe your eyes :)

> Using without Internet is yet another unfeasible use case

Do you already deny the existence of local and internal corporate networks? ;)

> you can download yourself after doing the backup

So it's about not just automatically making a backup but also automatically restoring it.
