### ISSUE TITLE
Feature Request: Multiple "Target App" Filter (aka. App Whitelist)

### ISSUE THREAD

**Issue by hjkcai** [emanuele-f/PCAPdroid#394]
PCAPdroid currently has blacklist mode, and filter for  ONE app mode. It would be nice and convenient to have handy number of whitelisted apps being captured at the same time. 

Thanks for the awesome app!

**Comment by emanuele-f** [comment]
Hello, thanks for your feedback. This is a duplicate of https://github.com/emanuele-f/PCAPdroid/issues/146
