### ISSUE TITLE
Support standard device sizes

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#4]
The app layout should be adapted to the standard device sizes. In particular, the horizontal orientation should be fixed.

**Comment by spvkgn** [comment]
Can't get the start button

![Screenshot_2020-02-12-21-06-55](https://user-images.githubusercontent.com/4147135/74353585-f3b31d80-4ddb-11ea-9e71-1acc92250cb9.png)

**Comment by emanuele-f** [comment]
Layout for your device should be fixed in 8c89b5508aa5d0c1a87acdb3a7cf35e67fad6ddb . Android studio does not provide a preview for you device size, does it work?

**Comment by spvkgn** [comment]
It doesnt, updated to v1.2.3 - it is the same as in previous version

**Comment by emanuele-f** [comment]
How many inches is your device screen? That is needed to calculate its DPI (https://www.sven.de/dpi)

**Comment by spvkgn** [comment]
4,34 in, 240 dpi. Please see [screenshot](https://i.imgur.com/wP6nIFV.png)

**Comment by emanuele-f** [comment]
With f862e8fe05af731eea95a56c27865dd10717dfc0 the start button is now located in the action bar, so this issue is solved. This will be available in the next app release.
