### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Boogerflick2020** [emanuele-f/PCAPdroid#415]
[I] 21/Feb/2024 00:03:36 - [PCAPdroid] Build type: GITHUB
[W] 21/Feb/2024 00:03:49 - [Main] Capture start failed
[I] 21/Feb/2024 00:04:54 - [CaptureService] Missing capture settings, using SharedPrefs
[I] 21/Feb/2024 00:04:54 - [CaptureService] Private DNS: disabled
[I] 21/Feb/2024 00:04:54 - [CaptureService] Private DNS: disabled
[I] 21/Feb/2024 00:04:54 - [Geolocation] Geolocation is not available
[I] 21/Feb/2024 00:04:54 - [CaptureService] Using DNS server 8.8.8.8
[I] 21/Feb/2024 00:04:54 - Starting packet loop
[I] 21/Feb/2024 00:04:54 - [CaptureService] reloading TLS decryption whitelist
[I] 21/Feb/2024 00:04:56 - [MitmAddon] Service connected
[I] 21/Feb/2024 00:04:56 - [MitmAddon] Send stop message
[I] 21/Feb/2024 00:04:56 - [MitmReceiver] Receiving data...
[I] 21/Feb/2024 00:04:56 - [MitmReceiver] MITM proxy is running

**Comment by emanuele-f** [comment]
Hello, PCAPdroid version used? Can you post a screen recording about the issue?

**Comment by emanuele-f** [comment]
No reply received, closing
