### ISSUE TITLE
Activity Monitor

### ISSUE THREAD

**Issue by Boogerflick2020** [emanuele-f/PCAPdroid#420]
Device

Identifiers
Pseudo ID: ffffffff-e76f-903b-ffff-ffffef05ac4a
User agent: Mozilla/5.0 (Linux; Android 14; SM-A536U Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36__Dalvik/2.1.0 (Linux; U; Android 14; SM-A536U Build/UP1A.231005.007)

NFS
Present: Yes
Enabled: No

Display
Display Resolution: 2159x1080
Screen Density: unknown
Screen Size: 5.93
Screen Refresh rate: 60.00 Hz

Date
Date: Mar 4, 2024
Time: 14:11:19
Uptime: 08:06:19

CPU
ABIS x32: armeabi-v7a_armeabi
ABIS x64: arm64-v8a
ABIS: arm64-v8a_armeabi-v7a_armeabi
Manufacturer: samsung
Model: SM-A536U
OS Codename: unknown
OS Version: 14
Language: en
Display Version: UP1A.231005.007.A536USQS9DXA9
Radio Version: A536USQS9DXA9
Product: a53xsqx
Board: s5e8825
Hardware: s5e8825
Device Rooted: No
Loader: A536USQS9DXA9
Brand: samsung
Host: SWDK6007
Release: 14
Codename: REL
SDK version: 34
Build ID: UP1A.231005.007
Core: null
Device type: Phone
Phone type: GSM
Orientation: Portrait

**Comment by Boogerflick2020** [comment]
I can't take these out fast enough and I have been blocked from the localhost

**Comment by emanuele-f** [comment]
Hello, please explain

**Comment by emanuele-f** [comment]
@Boogerflick2020 any news?

**Comment by Boogerflick2020** [comment]
I have been used to test this stuff out
They don't care about privacy. I can't 
Do anything about the broadcast. I 
I tried getting Samsung tech help 
Today but it didn't work. The woman 
Foreign and wasn't understanding what
I was saying. I can't take this anymore 
I am going to kill myself. SO.E

**Comment by Boogerflick2020** [comment]
I downloaded android studio and it had a hypervision program with it that took the laptop over so fast and it was smart enough to keep from being exported to a usb drive. It was a Google program

**Comment by emanuele-f** [comment]
This does not seem related to PCAPdroid, closing
