### ISSUE TITLE
Log: [AppsResolver] Could not retrieve package

### ISSUE THREAD

**Issue by smexyy** [emanuele-f/PCAPdroid#424]
Hello, I can see in log that pcap trying to retrieve (( uninstalled app already ))

![Screenshot_20240329-172140~2](https://github.com/emanuele-f/PCAPdroid/assets/135754251/512df28f-1d3c-4238-82ec-3a76c54c428c)

I tried { force stop app - clear cache - restart the phone } but still trying to retrieve specific packages I unistalled a week ago.

Info: Android 13 - pcap 1.7.0

**Comment by emanuele-f** [comment]
Hello, this was a bug, fixed in version 1.7.1 . Please note that this release is not currently available on Google Play, due to a pending review on their side
