### ISSUE TITLE
sslkeylogfile.txt produces "Duplicated entry" warnings in scapy, fails to decrypt traffic

### ISSUE THREAD

**Issue by dkbarn** [emanuele-f/PCAPdroid#426]
I am using PCAPdroid v1.7.1. I have set up everything necessary for mitmproxy, CA certificate installation, and have enabled decryption of TLS traffic.

I am monitoring a single targeted app. When I stop the live capture, it saves out a .pcap file and a sslkeylogfile.txt. In the Connections tab, I can see all of the HTTPS traffic that it captured, and I can see that the **payloads are decrypted**.

However, the sslkeylogfile.txt format that is generated does not seem to be valid. The contents of the file look like this (secrets removed):
```
CLIENT_RANDOM <token> <token>
CLIENT_RANDOM <token> <token>
CLIENT_RANDOM <token> <token>
CLIENT_RANDOM <token> <token>
CLIENT_RANDOM <token> <token>
CLIENT_RANDOM <token> <token>
```

When I try to load this using scapy, it produces a bunch of warnings:
```
WARNING:scapy.runtime:Duplicated entry for CLIENT_RANDOM !
WARNING:scapy.runtime:Duplicated entry for CLIENT_RANDOM !
WARNING:scapy.runtime:more Duplicated entry for CLIENT_RANDOM !
```
It doesn't like the fact that CLIENT_RANDOM is repeated several times in this file. Here is the code that scapy uses to parse these files: https://github.com/guedou/scapy-issues/blob/8ec40a2f455de66587053dc8fecae195931c1942/scapy/layers/tls/session.py#L32-L72

Sample code for how I am loading this in scapy (as copied from https://github.com/secdev/scapy/pull/3374#issue-1005099541):
```python
from scapy.all import *

load_layer("tls")
conf.tls_session_enable = True
conf.tls_nss_filename = "sslkeylogfile.txt"
pcap = rdpcap("PCAPdroid_xxxx.pcap")
```

In addition to these warnings, the TLS application data packets are not actually being decrypted. The same is true when I try to use this sslkeylogfile.txt inside Wireshark.

I'm happy to provide example sslkeylogfile.txt and companion .pcap file privately, if that would help to debug the issue.

**Comment by emanuele-f** [comment]
Maybe this can help: https://github.com/altafinance/ushark
