### ISSUE TITLE
PCAPdroid Trailer not work,lua plugin is  loaded normally

### ISSUE THREAD

**Issue by RokasUrbelis** [emanuele-f/PCAPdroid#428]
Hi,the file captured using pcapdroid does not seem to have a fake Ethernet head,the lua plugin is loaded normally,but the pcapng file doesn't seem to work,appname not displayed.
![image](https://github.com/emanuele-f/PCAPdroid/assets/48517501/61d56c37-fdcc-4ebf-9730-8704e472c410)
wireshark version: Version 4.2.2 (v4.2.2-0-g404592842786).
OS: windows 11

**Comment by emanuele-f** [comment]
Hello, please post your "Build info", that you access via the info icon in the the About page. Does it work if you disable the pcapng format?

**Comment by RokasUrbelis** [comment]
Disabling the pcapng format does not seem to resolve the issue, as it still does not work.
![443ee0ef60bb6f511e94b482d0c6c443](https://github.com/emanuele-f/PCAPdroid/assets/48517501/a3fa57c1-21ea-4d38-bb14-c6514e55a253)

**Comment by RokasUrbelis** [comment]
Build type: playstore
Build version: 1.7.2
Build date: 2024-04-21 00:10:27
Current date: 2024-05-06 19:52:37
Device: HUAWEI ALN-AL10
OS version: Android 12 (SDK 31)


DumpMode: PCAP_FILE
FullPayload: false
TLSDecryption: false
TLSSetupOk: true
CAInstallSkipped: true
BlockQuic: NEVER
RootCapture: false
Socks5: false
BlockPrivateDns: true
CaptureInterface: @inet
MalwareDetection: false
Firewall: false
PCAPNG: false
BlockNewApps: false
TargetApps: []
IpMode: BOTH
Trailer: false
StartAtBoot: false
PrivateDnsMode: disabled
MitmBatteryOptimized: false
![df19727cd7816ed1dc121b80b7394008](https://github.com/emanuele-f/PCAPdroid/assets/48517501/fa4ac4e6-1eaf-40cb-8284-628ee9e4402b)

**Comment by emanuele-f** [comment]
The PCAPdroid trailer option is disabled, you need to enable it

**Comment by emanuele-f** [comment]
This seems a bug, I will try to reproduce this

**Comment by RokasUrbelis** [comment]
Okay, I really appreciate your response,this project has solved many of my problems, and I fully support it
