### ISSUE TITLE
Garbage characters in PCAPdtoid trailer app name

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#435]
See https://github.com/emanuele-f/PCAPdroid/issues/428#issuecomment-2097458571

**Comment by emanuele-f** [comment]
@Qpp0 can you try changing this line `base.ASCII` to `base.UNICODE` [here](https://github.com/emanuele-f/PCAPdroid/blob/master/tools/pcapdroid.lua#L33) in the wireshark plugin, to see if it works?

**Comment by Qpp0** [comment]
> @Qpp0 can you try changing this line `base.ASCII` to `base.UNICODE` [here](https://github.com/emanuele-f/PCAPdroid/blob/master/tools/pcapdroid.lua#L33) in the wireshark plugin, to see if it works?

@emanuele-f 
I have already tried doing it. I’m not sure if it’s related to the Lua version used by Wireshark. In fact, by right-clicking on ‘appname’ and selecting ‘Show Packet Bytes,’ choosing UTF-8 encoding, it displays correctly.”
![image](https://github.com/emanuele-f/PCAPdroid/assets/93501907/2fc64b53-dbdc-4546-bb6c-9a10c0c0d846)

**Comment by emanuele-f** [comment]
@Qpp0 please you try this other change, other than `base.UNICODE` also modify line 54 to `local appname = trailer(8, 20):raw()`. Here is the full diff:

```diff
diff --git a/tools/pcapdroid.lua b/tools/pcapdroid.lua
index 0cb2c52a..c0127cbf 100644
--- a/tools/pcapdroid.lua
+++ b/tools/pcapdroid.lua
@@ -30,7 +30,7 @@ local fields = {}
 
 fields.magic   = ProtoField.uint32("pcapdroid.magic", "Magic", base.HEX)
 fields.uid     = ProtoField.int32("pcapdroid.uid", "UID", base.DEC)
-fields.appname = ProtoField.string("pcapdroid.appname", "App name", base.ASCII)
+fields.appname = ProtoField.string("pcapdroid.appname", "App name", base.UNICODE)
 
 pcapdroid.fields = fields
 
@@ -51,7 +51,7 @@ function pcapdroid.dissector(buffer, pinfo, tree)
     return
   end
 
-  local appname = trailer(8, 20):string()
+  local appname = trailer(8, 20):raw()
   local subtree = tree:add(pcapdroid, buffer(), string.format("PCAPdroid, App: %s", appname))
 
   subtree:add(fields.magic, trailer(0, 4))
```

**Comment by Qpp0** [comment]
> ```diff
> local appname = trailer(8, 20):raw()
> ```

Problem solved!

**Comment by emanuele-f** [comment]
Thanks for confirming
