### ISSUE TITLE
Can you add a function to transfer all TCP data to the remote mitmproxy (or other proxy)?

### ISSUE THREAD

**Issue by ihbing** [emanuele-f/PCAPdroid#44]
Can you add a function to transfer all TCP data to the remote mitmproxy (or other proxy)?

**Comment by emanuele-f** [comment]
What is your use case? You can already receive the traffic remotely via the [UDP exported mode](https://emanuele-f.github.io/PCAPdroid/dump_modes#24-udp-exporter)

**Comment by ihbing** [comment]
Intercept and modify data on the computer side.

**Comment by ihbing** [comment]
this is okay too.

**Comment by emanuele-f** [comment]
Implemented in b02989598f93c2bc49dbf8bd645efd39ee85d4fb . You can now use the official mitmproxy in socks5 mode (e.g. `mitmproxy --mode socks5 --listen-port 8080`) or any SOCKS5 proxy to intercept (and possibly decrypt) all the TCP traffic.

This will be part of the next release. If you want to use it now, you can install the [debug APK](https://github.com/emanuele-f/PCAPdroid/blob/2d626b50d01e73632a5a30285c34e14bb74c8786/PCAPdroid-debug-b029895.apk).
