### ISSUE TITLE
How to view PAYLOAD

### ISSUE THREAD

**Issue by jujubeja** [emanuele-f/PCAPdroid#452]
enabled Full payload , TLS decryption 
Still can't see the full link. raw.githubusercontent.com

![Screenshot_20240713-080936](https://github.com/user-attachments/assets/f511cabc-c94b-419f-b2c1-a16d29f8f2b0)

**Comment by emanuele-f** [comment]
You need to decrypt the sata, check out https://emanuele-f.github.io/PCAPdroid/tls_decryption for details

**Comment by jujubeja** [comment]
> You need to decrypt the sata, check out https://emanuele-f.github.io/PCAPdroid/tls_decryption for details

It doesn't help that no one but you, the project developer, knows anything about the https decryption rules.
