### ISSUE TITLE
Add option to modify network speed

### ISSUE THREAD

**Issue by RedAuburn** [emanuele-f/PCAPdroid#453]
it'd be useful to have a setting that allows to simulate slow connections, this would be useful for testing how an app handles slow connections while developing :)

**Comment by emanuele-f** [comment]
Hello, although feasible, this seems more appropriate for a dedicated app, to introduce semi-random drops and/or delays in order to test how apps behave. Let's keep this open but I don't see a good fit for PCAPdroid.
