### ISSUE TITLE
Android 11 - KEY_USAGE_BIT_INCORRECT mitmproxy certificate

### ISSUE THREAD

**Issue by koh-osug** [emanuele-f/PCAPdroid#47]
I was trying to intercept some TLS with the modified version of the mitmproxy. I was not successful and created a [simple demo application](https://github.com/koh-osug/TestMITMProxy) executing a query with OkHttp. There seems to be an issue with the mitmproxy certificate.

The CA certificate has these key usages:

>             X509v3 Extended Key Usage: 
>                 TLS Web Server Authentication, TLS Web Client Authentication, E-mail Protection, Time Stamping, Microsoft Individual Code Signing, Microsoft Commercial Code Signing, Microsoft Trust List Signing, Microsoft Server Gated Crypto, Microsoft Encrypted File System, Netscape Server Gated Crypto
>             X509v3 Key Usage: critical
>                 Certificate Sign, CRL Sign
> 

Maybe it is also complaining about the generated server certificate. BoringSSL is failing at this line: https://github.com/google/boringssl/blob/master/ssl/ssl_cert.cc#L608

> 2021-03-12 03:02:26.785 30566-30621/com.gigsky.testmitmproxy E/com.gigsky.testmitmproxy.MainActivity: Error
>     javax.net.ssl.SSLHandshakeException: Read error: ssl=0x74b41d8058: Failure in SSL library, usually a protocol error
>     error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT (external/boringssl/src/ssl/ssl_cert.cc:610 0x740ee2505a:0x00000000)
>         at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:362)
>         at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:919)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
>         at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
>         at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
>         at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
>         at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
>         at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
>         at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
>         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
>         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
>         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
>         at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
>         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
>         at okhttp3.RealCall.execute(RealCall.java:81)
>         at com.gigsky.testmitmproxy.MainActivity.lambda$testCall$4$MainActivity(MainActivity.java:74)
>         at com.gigsky.testmitmproxy.-$$Lambda$MainActivity$bZPwyLI6MhGRb52InxteaVjycNk.run(Unknown Source:2)
>         at java.lang.Thread.run(Thread.java:923)
>      Caused by: javax.net.ssl.SSLProtocolException: Read error: ssl=0x74b41d8058: Failure in SSL library, usually a protocol error
>     error:1000012e:SSL routines:OPENSSL_internal:KEY_USAGE_BIT_INCORRECT (external/boringssl/src/ssl/ssl_cert.cc:610 0x740ee2505a:0x00000000)
>         at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
>         at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
>         at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
>         at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
>         	... 29 more

**Comment by emanuele-f** [comment]
This applicates to your android version, however I don't think is related to your issue: https://emanuele-f.github.io/PCAPdroid/tls_decryption#32-decryption-after-android-7. If this does not help, please open an issue on mitmproxy.

**Comment by koh-osug** [comment]
I have done the necessary steps and added a security config already. This does not seem to be the problem. I will create the issue with the upstream mitmproxy project? Because I'm using the tunnel mode they might not handle it, but I will try it there.

**Comment by emanuele-f** [comment]
Yes please, I don't know how to help on this subject. Tunnel mode should not be relevant for this issue.

**Comment by emanuele-f** [comment]
Related issue: https://github.com/mitmproxy/mitmproxy/issues/4501

**Comment by koh-osug** [comment]
To track down the problem, I tried to compare the master branches of mitmproy with this version, but it seems they differ a lot. The interesting part for me would be the implementation of the tunnel mode. The directory structure is different now, e.g. all in the `modes` directory seems to be now in the `modes.py` file. What is the tunnel mode doing? Can it be combined with a HTTP(s) proxy? I want to support [Forked improved version of LittleProxy-mitm](https://github.com/koh-osug/LittleProxy-mitm) and include it directly in Android without an external proxy. The python solution of mitmproxy seems to be no easy or not at all to be running inside Android.

**Comment by emanuele-f** [comment]
I based it on the master branch but later switched to v6.0.2, you can easily compare the changes here: https://github.com/mitmproxy/mitmproxy/compare/v6.0.2...emanuele-f:master . In practice, the tunnel mode adds the original destination IP and port at the start of each TCP connection. An alternative approach based on a socks proxy is discussed in #44.

It would be great to have an integrated solution inside PCAPdroid itself. Such library should be slim (in terms of executable size), should support TLS 1.3 and should be actively maintained. Please follow up on #9 on this topic.
