### ISSUE TITLE
[QUESTION] PCAPdroid on an Oculus Quest 2

### ISSUE THREAD

**Issue by manugarri** [emanuele-f/PCAPdroid#50]
Is it possible to install PCAPdroid on the Oculus Quest 2 headset? Is android based, and tools like adb work.

I apologize if this has been documented somewhere :)

**Comment by emanuele-f** [comment]
You can try the standard way to install apps with "adb install akp_path", however I think the app should be somehow adapted to run on your device in a similar way I did to add Android TV support. I definitely wish to support more devices, so I will provide any useful info to properly support your device!

**Comment by emanuele-f** [comment]
No feedback received

**Comment by manugarri** [comment]
@emanuele-f sorry, i never got around testing this :/ still would like to test it in the future
