### ISSUE TITLE
UDP broadcast Error — unable to connect to IoT device via PCAPdroid's VPN

### ISSUE THREAD

**Issue by okdimok** [emanuele-f/PCAPdroid#51]
Hi!
I am trying to capture the API of my LED backpack. It acts as a Wi-Fi hotspot and is controlled by a special app [LED Space](https://play.google.com/store/apps/details?id=com.yj.led&hl=en). When I am enabling the VPN for the capture, the app is unable to connect to the backpack. I think, the reason is in broadcast requests, like the one below. 

```
App: LED Space (10476)
Protocol: UDP
Source: 10.215.173.1:9001
Destination: 255.255.255.255:9090
Status: Error
Bytes: 0 B down — 42 B up
Packets: 0 down — 1 up
Duration: < 1 s
First Seen: 03/29/21 11:53:18
Last Seen: 03/29/21 11:53:18
```

**Comment by emanuele-f** [comment]
This should be fixed in 1bb6ae31654b9d5bdbcc8d6488ffbf211c3eda1f . Can you try the debug apk https://github.com/emanuele-f/PCAPdroid/blob/debug-apks/PCAPdroid-debug-1bb6ae3.apk and confirm it works? Please note that you will need to manually uninstall the old apk in order to install this.

**Comment by okdimok** [comment]
Thank you for such a quick response!

I've installed the debug apk and I was able to capture the traffic from the app to the backpack and back, if the connection had been established before the capture start.
However, if I first started the capture and then tried to initiate the connection, it didn't work.

So this is the capture, when I 
1. Connect successfully to the backpack
2. Start the PCAP capture
3. Send some commands from the app to the backpack
[capture 1](https://drive.google.com/file/d/1RzZodUXLJOGuXk78Ns_pGpdE2VBCfe3C/view?usp=sharing)

And this is the capture, where I
1. Start the PCAP capture
2. Cannot connect to the backpack
[capture 2](https://drive.google.com/file/d/1qfXXDcskc4APTLi3juDHpPCuZ-FpvLiP/view?usp=sharing)

I guess the reason may be the source of the response, which is 255.255.255.255
![image](https://user-images.githubusercontent.com/2771762/112875520-f995bc00-90cc-11eb-8219-4547e8dd46bd.png)

**Comment by emanuele-f** [comment]
"capture 2" shows that the UDP connection is now handled correctly. I've also tested it with a UDP tester app on android and I can correctly receive the UDP broadcast response.

The led space application may employ some checks on the local network which prevent the connection from happening, e.g. 192.168.43.1 is not into the main network of the phone, which is 10.215.173.0/24 due to the VPN. For this reason I would consider this issue as solved, unless you can prove that the UDP broadcast is not handled correctly.

**Comment by okdimok** [comment]
I think [this line](https://github.com/emanuele-f/zdtun/blob/a29c548af21f5e09a6111f3c08b7f8edf804991b/zdtun.c#L393) could be changed to something like
```
if(conn->tuple.dst_ip.ip4 == INADDR_BROADCAST) {
 ip->saddr = gateway_IP;
}
else ip->saddr = conn->tuple.dst_ip.ip4;
```
to simulate a more real response, but my applied goal is now achievable, thanks to you, so I'm OK with closing the bug.

**Comment by emanuele-f** [comment]
You assume that the reply comes from the gateway IP, but this may not be the case, for example it may come from another device into your LAN.
