### ISSUE TITLE
Install instruction fix mitmproxy installation

### ISSUE THREAD

**Issue by koh-osug** [emanuele-f/PCAPdroid#56]
On the page https://emanuele-f.github.io/PCAPdroid/tls_decryption instead of using:

~~~
git clone https://github.com/emanuele-f/mitmproxy
cd mitmproxy
sudo python3 setup.py install
~~~

Use:

~~~
git clone https://github.com/emanuele-f/mitmproxy
cd mitmproxy
sudo pip3 install .
~~~

The last line enables to uninstall the application with `sudo pip3 uninstall mitmproxy`, otherwise the installation must be done manually, which would require to know where all files have been installed.

**Comment by emanuele-f** [comment]
Thanks, I've updated the docs.
