### ISSUE TITLE
upload big file when PCAPdroid on

### ISSUE THREAD

**Issue by baibaip** [emanuele-f/PCAPdroid#59]
hi, not a bug more of a request. here is,
step 1. install PCAPdroid app, start VPN connect.
        2. open my web page, upload a big file, like 100MB
        3. wait a minute, then upload fail
        4. stop VPN connect, then upload a big file and upload success
        5. start VPN connect, then upload a small file, like 100KB, and upload success
does a limit size in somewhere sets too slow?
Thanks and thanks for creating this very useful app

ps: PCAPdroid 1.3.4 from github.

**Comment by emanuele-f** [comment]
Please note the following:

1. It seems like you are using a custom upload feature, implemented in https://github.com/baibaip/XDForwarder . I only accept issues for the official PCAPdroid
2. If you are a commercial, I expect you to contribute either via pull requests, donations or paid consulting. You can contact me privately and I will be happy to help you troubleshooting this.
3. PCAPdroid is licensed under GPLv3. You are not allowed to remove the copyright notice or take credit for the project, I'm referring to (https://github.com/baibaip/XDForwarder/commit/50f761fd428d77b92c4ccc954fe1896d648da73a#diff-d9c30b0c0a46ff73de30b4ec09e9219f1edad9a9ce584661d8170e5545d6aa50)

**Comment by baibaip** [comment]
sorry, i use the official PCAPdroid to do this test.
XDForwarder is my private project, and i am not a commercial. i am learning how to capture packets by vpn, then i found this useful app. this is my research project, and thanks for creating this.

**Comment by emanuele-f** [comment]
Free software encourages modifications but a removed attribution is one of the very few things that can make a developer angry! It's like stealing the time and effort I've put in it. So if you like the project, giving attribution while showing it to other people is the least that you can do to support it.

I think the upload issue was fixed in the latest commits, otherwise provide instructions to reproduce

**Comment by baibaip** [comment]
I apologize for my behavior.
And thanks again. I will use the official PCAPdroid to do the rest work.
