### ISSUE TITLE
udp_receiver

### ISSUE THREAD

**Issue by mabox965** [emanuele-f/PCAPdroid#6]
Hello !!

When I use the command 

udp_receiver.py -p 1234 | wireshark -k -i -"

I have following the error messages 
(terminal)
"13:36:58.902     Main Warn QXcbConnection: XCB error: 3 (BadWindow), sequence: 915, resource id: 35652163, major code: 40 (TranslateCoords), minor code: 0"

(wireshark)
Couldn't run /usr/bin/dumpcap in child process: Permission non accordée

Thanks for your contribution
ma

**Comment by emanuele-f** [comment]
Hi, please try this: https://gist.github.com/MinaMikhailcom/0825906230cbbe478faf4d08abe9d11a

**Comment by emanuele-f** [comment]
Closing this as no feedback was received.
