### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by emanuele-f** [emanuele-f/PCAPdroid#77]
@akihironagai @mezysinc @NEK-RA can you please update the translations for the new release?

**Comment by mezysinc** [comment]
@emanuele-f would you be able to always merge new, updated & missing strings (the same way you add them to the main 'values' in English) to ptbr.
That would speed translating process up by x100. If not I'll do it manually, but let me know if you don't mind doing it...

**Comment by emanuele-f** [comment]
Here are the new ptbr strings to translate:
```
    <string name="show_whitelisted">Show whitelisted connections</string>
    <string name="hide_whitelisted">Hide whitelisted connections</string>
    <string name="whitelist">Whitelist</string>
    <string name="edit_whitelist">Edit Whitelist</string>
    <string name="whitelist_action">Whitelist…</string>
    <string name="whitelist_empty">The whitelist is empty.\nYou can long press a connection to whitelist it.</string>
    <string name="n_selected">%1$d selected</string>
    <string name="select_all">Select all</string>
```

I always add the new strings at the bottom of the English file, so that it is easy to spot what to translate. I periodically clean up the unused strings.
