### ISSUE TITLE
Running PCAP on Virtual device.

### ISSUE THREAD

**Issue by Rolland-K** [emanuele-f/PCAPdroid#96]
when I run pcap on genymotion,
it captures source ip as 10.215.173.1
I know this is the virtual interface, I need to get real address such as 192.168....
so I tried to give root permission, and it shows this toast.
"pcapd damon did not spawn"
please let me know is it possible to capture real source ip address?
and is it possible to give root permission on virtual device (genymotion, Emulator)

one more question.
Can I capture data transmitted over LTE? Or wifi only?

**Comment by emanuele-f** [comment]
First of all try the [latest debug apk](https://github.com/emanuele-f/PCAPdroid/blob/9bb380bde5cc918ef791487605288fb6623918d7/PCAPdroid-debug-dfeb9e5.apk?raw=true) which contains some fixes for root mode (the new official release with the fixes will be published soon). Then you can look at the "Root Log" which is available in the left navigation drawer once the root capture is started to see possible error messages. Please report these errors here.

I tested it on the official Android emulator (rooted with https://github.com/shakalaca/MagiskOnEmulator, beware of https://github.com/shakalaca/MagiskOnEmulator/issues/43) and it works great in root mode.

**Comment by emanuele-f** [comment]
Closing as no feedback has been received. Please remember to close the issue when satisfied.
